### ISSUE TITLE
Can't read data in swmr mode while writer has the file open

### ISSUE THREAD

**Issue by technitium** [h5py/h5py#1089]
* Operating System (Windows 10, and Ubuntu 18.04)
 * Python version 3.7
 * Where Python was acquired (python installer for windows, system python in ubuntu)
 * h5py version 2.8
 * HDF5 version 1.10.0
 
I tried a simple example of h5py SWMR mode, and got unexpected behavior:

The following writer script writes to an h5 file using the SWMR mode of h5py library:

    import h5py
    import time

    print("Starting")
    f = h5py.File('/mnt/c/files/temp.h5', 'w', libver='latest')
    f.swmr_mode = True
    ncols = 6
    grp = f.create_group('test')
    dset = grp.create_dataset('dat', chunks=(1,ncols), maxshape=(None,ncols), data=[[1]*ncols])
    dset.flush()
    print("Sleeping")
    time.sleep(10)
    f.close()
    print("Closed")

While the writer script has the file open and data written (between Sleeping and Closed prints), if we try reading from the h5 file using:

    import h5py

    f = h5py.File("c:/files/temp.h5", 'r', libver='latest', swmr=True)
    grps = list(f.keys())
    print(grps)
    if len(grps) > 0:
        grp=f[grps[0]]
        dsets = list(grp.keys())
        print(dsets)
        if len(dsets) > 0:
            ds = grp[dsets[0]]
            print(ds[:])
    f.close()

We don't see any keys in the file f.

However, once the writer finishes running and closes the file, then the reader is able to read the data that was written to the file. The whole point of SWMR mode is to be able to simultaneously read while the writer is writing to a file. Am I implementing the code correctly, or is there a bug in the library?

**Comment by tacaswell** [comment]
You need hdf5 1.10 for smwr to work.

**Comment by technitium** [comment]
I tried it with hdf5 1.10, but it still doesn't work. Did the code sample give the desired behavior in your platform? Also, I know that swmr is working on my environment since the following code gives the desired swmr behavior:

    import h5py
    import time

    print("Starting")
    f = h5py.File('/mnt/c/files/temp.h5', 'w', libver='latest')
    f.swmr_mode = True
    ncols = 6
    dset = f.create_dataset('dat', chunks=(1,ncols), maxshape=(None,ncols), data=[[1]*ncols])
    dset.flush()
    print("Sleeping")
    time.sleep(10)
    f.close()
    print("Closed")

and this is readable with:

    import h5py

    f = h5py.File("c:/files/temp.h5", 'r', libver='latest', swmr=True)
    print(f['dat'][:])

between the 'Sleeping' and 'Closed' prints. However, the moment I add a group to the file and create the dataset within the group, swmr stops working.

**Comment by epourmal** [comment]
Raj,

Current HDF5 SWMR doesn’t allow modification of the file structure, i. e., groups or datasets cannot be added. Only data to the existing datasets can be added.

Elena



Sent from my iPhone

On Aug 30, 2018, at 7:55 PM, Raj Ghosh <notifications@github.com<mailto:notifications@github.com>> wrote:


I tried it with hdf5 1.10, but it still doesn't work. Did the code sample give the desired behavior in your platform? Also, I know that swmr is working on my environment since the following code gives the desired swmr behavior:

import h5py
import time

print("Starting")
f = h5py.File('/mnt/c/files/temp.h5', 'w', libver='latest')
f.swmr_mode = True
ncols = 6
dset = f.create_dataset('dat', chunks=(1,ncols), maxshape=(None,ncols), data=[[1]*ncols])
dset.flush()
print("Sleeping")
time.sleep(10)
f.close()
print("Closed")


and this is readable with:

import h5py

f = h5py.File("c:/files/temp.h5", 'r', libver='latest', swmr=True)
print(f['dat'][:])


between the 'Sleeping' and 'Closed' prints. However, the moment I add a group to the file and create the dataset within the group, swmr stops working.

**Comment by technitium** [comment]
Thanks! The issue has been resolved. The desired behavior was obtained upon setting:

    f.swmr_mode = True
after all the groups and datasets were created.

**Comment by epourmal** [comment]
Yes, this is how SWMR works.

Sent from my iPhone

On Aug 30, 2018, at 8:30 PM, Raj Ghosh <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks! The issue has been resolved. The desired behavior was obtained upon setting:

f.swmr_mode = True


after all the groups and datasets were created.
