### ISSUE TITLE
API proposal: break up special_dtype into three functions

### ISSUE THREAD

**Issue by takluyver** [h5py/h5py#1118]
The [special_dtype](http://docs.h5py.org/en/2.8.0/special.html) function takes one of three keyword arguments vlen/enum/ref. It's only legal to pass one, and the meaning of the parameter value and the implementation of the function entirely depend on which keyword is used. It's effectively three different functions combined under one name.

The name 'special' also isn't very meaningful. I can see from the docs that 'special' means types which can't be directly represented in numpy, but this definition is only helpful if you know numpy very well. A string doesn't feel 'special' to me, for instance.

So I think it would be clearer to split this up into three functions: `vlen_dtype(element_dtype)`, `enum_dtype(base_type, enum_vals)` and `ref_dtype(ref_class)`. As there are only two legal types for the last one, we could further split that up into constants `ref_dtype` and `region_ref_dtype`.

Of course, the `special_dtype` function would remain, so existing code using that would continue to work. But the documentation would point people to the separate functions.

**Comment by aragilar** [comment]
I guess the reasoning for having this as one function was that the metadata was stored the same way (so https://github.com/h5py/h5py/blob/master/h5py/h5t.pyx#L1799 works on all special types), the origin of this function isn't in git so I suspect if there's a deeper reason, everyone's probably forgotten it.

I agree with splitting out the functions (I wouldn't bother with creating a ref_dtype function, I'd have them as constants, with `special_dtype` returning the constant as needed). If we're going to change this, then I'd recommend changing the default vlen handing to not special-case `bytes` and `unicode`, and instead require specifying the encoding (`special_dtype` would still accept `bytes` and `unicode`, using ascii and utf-8 as the arguments to the new string dtype creator). This would avoid confusion due to how `str`is treated by `special_dtype` currently.
