### ISSUE TITLE
Can I resize the virtual layout?

### ISSUE THREAD

**Issue by gliese581gg** [h5py/h5py#1167]
To assist reproducing bugs, please include the following:
 * Operating System (e.g. Windows 10, MacOS 10.11, Ubuntu 16.04.2 LTS, CentOS 7) : Ubuntu16.04
 * Python version (e.g. 2.7, 3.5) : 3.5.2
 * Where Python was acquired (e.g. system Python on MacOS or Linux, Anaconda on
   Windows) : system
 * h5py version (e.g. 2.6) : 2.9
 * HDF5 version (e.g. 1.8.17) : unknown
 * The full traceback/stack trace shown (if it appears)

Hi! I have simple question.

Is there any way to resize the virtual layout?

I'm thinking about how to append new files to virtual dataset without building it from scratch

**Comment by jangarrevoet** [comment]
No you can not, but rebuilding a virtual dataset is a cheap operation.

**Comment by takluyver** [comment]
In terms of the high-level API, @jangarrevoet already said it: building a virtual dataset should be quick enough that you can just recreate it each time you want to add new files. If it's not, please provide details so that we can figure out whether it's a bug, something to provide a better API for, or a use case we don't want to support.

The VDS specification allows for one dimension to be unlimited, either supporting the source datasets growing in that dimension, or looking up an expanding sequence of files with numbers in the filenames. I think this is unnecessary complexity, and I didn't yet try to expose it in the high-level API in h5py.

**Comment by vasole** [comment]
We are also interested on this. We have the use case of acquiring images into different files. Those images have to be assembled into a unique dataset of shape (nframes, nrows, ncolumns). It would be desirable to create a virtual dataset where the first dimension could be growing as new files are arriving instead of having to wait until the whole acquisition is over...

**Comment by aragilar** [comment]
Given that the answer to "Can I resize?" is "no", I'm going to close this, and leave #1202 for the unlimited dimension part.
