### ISSUE TITLE
H5py does not compress

### ISSUE THREAD

**Issue by stefanhiemer** [h5py/h5py#1427]
Fedora 29
Python 3.74 system
 h5py    2.10.0
HDF5    1.10.4
Python  3.7.4 
GCC 8.3.1 20190223 (Red Hat 8.3.1-2)

Dear community,

I try to collect my simulation data in hdf5 files via h5py. When I zipped my data, it compressed by 50 %. When I tried the same with h5py the data either did not compress at all (gzip) or became considerable larger (zlf,szip).  I run python in a virtual environment (https://virtualenvwrapper.readthedocs.io/en/latest/index.html).

I attached a reduced script as well as example data (seed0).
[seed0.zip](https://github.com/h5py/h5py/files/3789492/seed0.zip)

[convert_to_hdf5_submit.zip](https://github.com/h5py/h5py/files/3789494/convert_to_hdf5_submit.zip)

It seems to me, that there does not happen any compression at all. Any suggestions would  be great help at this point.

Thanks and Regards
Stefan

**Comment by stefanhiemer** [comment]
You are right. I just checked my script for larger datasets found a mistake there. Once I resolved it, the compression worked. Still not far from great, but my data is simply not optimal for compression (at the moment). Thanks for your help and sorry for wasting your time on such a simple matter.

**Comment by takluyver** [comment]
gzip is pretty basic - you might get better compression with Blosc, available through the [hdf5plugin package](https://pypi.org/project/hdf5plugin/). But even so, it might just not be very compressible.

There's a trade-off because the data will only be accessible with the plugin, whereas gzip is built into HDF5 - depending on how you use the data that might matter or not.

**Comment by stefanhiemer** [comment]
Many thanks. I did not know this module. I will try it soon.
