### ISSUE TITLE
AttributeError: h5py.h5.H5PYConfig' has no attribute '__reduce_cython__'

### ISSUE THREAD

**Issue by prpeixoto** [h5py/h5py#1477]
Hello all,
 * Operating System Windows 10
 * Python version 3.7
 *  Windows
 * h5py version 2.10
* tensorflow version 2.0.0

I'm trying to load a previously saved tensorflow model that was saved using th5 extension on my program, however, when trying to import the tensorflow library, the error bellow is displayed. I've tried downgrading the h5py, and it didn't work. I also tried the newer version of tensorflow with no result. Does anyone have any idea what could be causing this? Thank you

The error displayed:
AttributeError("type object 'h5py.h5.H5PYConfig' has no attribute '__reduce_cython__'")

**Comment by michaelStettler** [comment]
So I am also having this issue and apparently one workaround would be to use h5py 2.7. Perhaps it may help you to try other versions. 

In my case though I don't know if it works since I get the following:  

> C:\Users\Michael\PycharmProjects\test_h5py\venv\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
>     C:\Users\Michael\AppData\Local\Temp\pip-install-wxsonm08\h5py\h5py\api_compat.h(27): fatal error C1083: Cannot open include file: 'hdf5.h': No such file or directory
>     error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

**Comment by tacaswell** [comment]
@prpeixoto That looks like an installation issue.  I suggest uninstalling and reinstalling h5py via which ever mechanism you are using

@michaelStettler That looks like you are trying to compile h5py from source but do not have the hdf5 headers available on your system.

**Comment by michaelStettler** [comment]
Thanks for your answer. May I ask if you could point me out to get the headers correctly ? 
Actually by continuing trying, I also realised that installing the 2.7 works perfectly fine with python 3.6

**Comment by tacaswell** [comment]
I suggest looking at the appveyor config files (https://github.com/h5py/h5py/blob/master/appveyor.yml) which show how we build h5py on windows for CI.

I am unfortunately not really qualified to answers how to get headers on windows beyond that.

**Comment by michaelStettler** [comment]
Thanks! I'll have a look
Quick update so far, it seems that downgrading to python 3.6 and h5py 2.7 does the trick for me. But I have to say it also feels like h5py may be involved in that issue since I got again the problem (which appears also a couple of times on stack overflow) when using again h5py 2.10 and python 3.6. 
It would be nice to know if something changed between 2.7 and 2.8, especially as in the commit for 2.8 it says:  - Minimum version of cython is now 0.23.

But so far at least I have no more error messages with:
python 3.6
tensorflow-gpu 2.1
h5py 2.7

I'll continue and edit my message if it all works fine for me.

**Comment by tacaswell** [comment]
I do not doubt that the built binary artifacts from h5py are involved, but I think the root of the issue is a miss-match between the other libraries.  This should be reported to who ever is providing your packages and possibly to the tensorflow folks.

I do not think there is anything we can do about this on the code side in h5py.

**Comment by michaelStettler** [comment]
I see, well thanks anyway

From my side, I confirm that my project runs with h5py 2.7.

**Comment by takluyver** [comment]
Can anyone reproduce this error without Tensorflow?

**Comment by 8Yury8** [comment]
Hi! I've got the same problem with Tensorflow 2.3.0.: ERROR: tensorflow 2.3.0 has requirement h5py<2.11.0,>=2.10.0, but you'll have h5py 2.7.0 which is incompatible. But I can't install it. Are there any channels to update it for Conda environment?

**Comment by ruczmz** [comment]
Open python or jupyter, spyder  with administrator rights

**Comment by takluyver** [comment]
Running Python as admin is unlikely to solve a problem like this in general, even if it happened to work in one specific case. It's also bad advice in general: code running as admin has more power to mess up your system.

**Comment by princyok** [comment]
Run `pip uninstall h5py` multiple times to remove multiple installations (this is in conda environment). 

Then run `conda install -c anaconda h5py`.

That fixed it for me.

**Comment by tacaswell** [comment]
Closing this issue as it is an installation issue and not anything we can fix at the source level.

**Comment by bernie6401** [comment]
thanks @princyok  for useful helping
indeed you can not use pip install the h5py, you have to use conda install instead

**Comment by shafaattahir** [comment]
I got the same issue, just you need to uninstall and then install it 'h5py'.

**Comment by tashrifbillah** [comment]
```bash
pip uninstall h5py
pip install h5py
```
worked for me. By the way, you may have to open your PowerShell with administrative privilege.

**Comment by tashrifbillah** [comment]
```bash
pip uninstall h5py
pip install h5py
```
worked for me. By the way, you may have to open your PowerShell with administrative privilege.

For the update to load in `jupyter-notebook`, I had to `Ctrl+C` the kernel and restart. This is surprising because I did not have to do this for other pip installed libraries as they were automatically available after installation.

**Comment by takluyver** [comment]
If you upgrade something that you have already imported, it's normal that you have to restart Python (restart the kernel, in Jupyter) to pick it up.

**Comment by transtrades** [comment]
> Run `pip uninstall h5py` multiple times to remove multiple installations (this is in conda environment).
> 
> Then run `conda install -c anaconda h5py`.
> 
> That fixed it for me.

YES THIS IS THE SOLUTION

**Comment by furkanozbilgin** [comment]
> Run `pip uninstall h5py` multiple times to remove multiple installations (this is in conda environment).
> 
> Then run `conda install -c anaconda h5py`.
> 
> That fixed it for me.

Correct Solution
