### ISSUE TITLE
Printing overview of hdf5 layout

### ISSUE THREAD

**Issue by thomasaarholt** [h5py/h5py#1539]
I sometimes use the HDFView tool to inspect the layout of a file, so that I can easier know how to access the bit of information that I am interested in. But downloading it can be slow and it's 200MB.

![image](https://user-images.githubusercontent.com/2721423/80193733-a512d280-8619-11ea-8661-65cb59815c87.png)

It would be nice if there was a built-in method (maybe a `h5py.utils.function()`) to print a tree similar to that on the left in the screenshot. It would additionally be nice to have such a function that also prints the name of attributes present in each object.

Does such a thing exist already? I'd be happy to contribute with a PR if wanted. For now I've written the following:

```python
def print_tree(group, print_attrs=False, i=0):
    'Print the names of groups, datasets and (optionally) attributes in an hdf5 file'
    delimiter = '  '
    if hasattr(group, 'keys'):
        for key, value in sorted(group.items()):
            print(i*delimiter, key)
            if print_attrs:
                if list(value.attrs): # may want to print empty lists anyway, consider removing
                    print((i+1)*delimiter, list(value.attrs))
            print_tree(value, print_attrs=print_attrs, i=i+1)
    else:
        print(i*delimiter, group)
```

**Comment by jangarrevoet** [comment]
Why not use h5ls -r <filename> to list the tree?
You can also dump the attribute using h5dump.
If you have them installed yet, you need to install the hdf5-tools package.

**Comment by thomasaarholt** [comment]
I wasn't aware of that, thank you. It seems to have installed itself when I installed the HDFView tool.

However, I'd still argue that this could be useful in h5py? There will probably be cases of users using python through jupyter notebooks, sometimes over server implementations like jupyterhub. There they may not have access to command line.

**Comment by takluyver** [comment]
[h5glance](https://github.com/European-XFEL/h5glance) is our take on this - including both a command line tool and a Jupyter notebook interface ([demo notebook](https://nbviewer.jupyter.org/github/European-XFEL/h5glance/blob/master/Demo.ipynb)).

IMO, there's enough nuances to doing convenient human inspection of HDF5 files that it makes sense to have a separate project for this rather than a utility function in h5py.

There are also [lots of other people working on various HDF5 viewers](https://github.com/panosc-eu/panosc/blob/master/Work%20Packages/WP4%20Data%20analysis%20services/resources/hdf5-viewers.rst). I think h5glance is possibly closest to what you're talking about in that it's fairly small and focused on inspecting the structure of the HDF5 file, rather than on visualising the data.

**Comment by thomasaarholt** [comment]
Thanks @takluyver that's the sort of thing I had in mind! That looks well-built, and I think it suits my requirements well. Thank you!
