### ISSUE TITLE
Use '.' filename in virtual datasets referring to their own file

### ISSUE THREAD

**Issue by asmeurer** [h5py/h5py#1546]
```py
>>> import h5py
>>> f = h5py.File('test.hdf5', 'w')
>>> f.create_dataset('base', data=[1, 2, 3])
<HDF5 dataset "base": shape (3,), type "<i8">
>>> layout = h5py.VirtualLayout(f['base'].shape)
>>> vs = h5py.VirtualSource(f['base'])
>>> layout[:] = vs[:]
>>> f.create_virtual_dataset('virtual', layout)
<HDF5 dataset "virtual": shape (3,), type "<f4">
>>> f['virtual'][:]
array([1., 2., 3.], dtype=float32)
```

```
$ mv test.hdf5 test2.hdf5
```

```py
>>> import h5py
>>> f = h5py.File('test2.hdf5', 'r')
>>> f['virtual'][:]
array([0., 0., 0.], dtype=float32)
```

It gives all 0s because the virtual dataset hard-codes the filename `test.hdf5`, which no longer exists. 

```py
>>> f['virtual'].virtual_sources()
[VDSmap(vspace=<h5py.h5s.SpaceID object at 0x11d8332f0>, file_name='test.hdf5', dset_name='/base', src_space=<h5py.h5s.SpaceID object at 0x11d833410>)]
```

So it just returns the empty buffer unchanged. I would have expected an error here instead. I looked into the h5py and hdf5 sources and I from what I could tell an error should be raised when a file isn't found. I can't really tell why it isn't.

I also would have expected it to use a relative filename by default when `VirtualSource` is passed a dataset (`'.'` can be used to reference the same file), but maybe there's a good reason not to do this.

```py
>>> print(h5py.version.info)
Summary of the h5py configuration
---------------------------------

h5py    2.10.0
HDF5    1.10.5
Python  3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:45:16)
[Clang 9.0.1 ]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   1.18.1
```

(this is actually the git h5py)

**Comment by asmeurer** [comment]
CC @scopatz

**Comment by takluyver** [comment]
It's been a recurring annoyance to me that problems accessing data for a virtual dataset show up as missing data rather than an error - see e.g. [this forum post](https://forum.hdfgroup.org/t/virtual-datasets-and-open-file-limit/6757) and [this one](https://forum.hdfgroup.org/t/virtual-dataset-in-read-write-file-missing-data-from-read-only-file/5647). This behaviour comes from HDF5 itself, so there's nothing h5py can do short of reimplementing the logic for reading virtual datasets independently, which is a road I don't want to go down.

I can guess at least part of the reason for this - virtual datasets allow for a sequence of numbered files/datasets of unknown length: `1.h5`, `2.h5`, etc., specified like `%0b.h5`, and there may be small gaps in the sequence, which are meant to be treated as missing data. But this still doesn't seem like enough reason to silence all errors.

I didn't know about using `'.'` to refer to the same file. @epourmal , is that an intentional feature which we can rely on? The [documentation of H5Pset_virtual](https://confluence.hdfgroup.org/display/HDF5/H5P_SET_VIRTUAL) suggests that it would just append a literal `.` to the prefix or the path of the file containing the virtual dataset.

**Comment by asmeurer** [comment]
Thanks. I guess I didn't pick up when reading the HDF5 sources that it does silence errors due to the % formatting. I guess this is an unfortunate side-effect of the API design in HDF5, and I agree there doesn't seem like much h5py can or should do about it. 

I didn't realize that the default buffer defaults to missing data. So I can set it to nan instead of the default 0 to at least give a better indication that something has gone wrong. 

> I didn't know about using '.' to refer to the same file. @epourmal , is that an intentional feature which we can rely on? The documentation of H5Pset_virtual suggests that it would just append a literal . to the prefix or the path of the file containing the virtual dataset.

Yeah I didn't know about the `'.'` thing either until I dug into the HDF5 source code. It isn't documented anywhere as far as I can tell.  It does seem to be an intentional feature https://github.com/HDFGroup/hdf5/blob/88a39adaa2e2a35ef385896cac6c209abc4f388f/src/H5Dvirtual.c#L928.

**Comment by takluyver** [comment]
Thanks, that definitely does look intentional.

@epourmal, any chance we could get it documented that `'.'` as the filename means the same file that the virtual dataset is in? As Aaron found, it looks very deliberate in the code, but neither of us have seen it in docs.

@asmeurer you might be interested in our tool [hdf5-vds-check](https://github.com/European-XFEL/hdf5-vds-check) - this is a little command which checks any virtual datasets in a file to see if their sources can be found and opened. It's obviously not ideal to check this separately, but it can be handy to quickly find problems.

**Comment by vasole** [comment]
@takluyver I contacted the HDF Group help concerning if we could rely on that usage of the dot to refer to the same file and I got an affirmative answer. @tacaswell was in copy of the mail exchange.

**Comment by epourmal** [comment]
> 
> 
> @epourmal, any chance we could get it documented that `'.'` as the filename means the same file that the virtual dataset is in? As Aaron found, it looks very deliberate in the code, but neither of us have seen it in docs.
> 
Yes, will make it more prominent. Barbara, our Help Desk person, is looking into it. Thank you for reporting!

**Comment by takluyver** [comment]
Thanks @vasole and @epourmal. I'll update the issue title and keep this as a feature request to use `'.'` when appropriate

I think we'd do this by checking for the filename in `.create_virtual_dataset()`, because we don't know what file the dataset will be in before then.

**Comment by takluyver** [comment]
You can work around this by using `VirtualSource('.', ...)`, but you lose the convenience of passing in a dataset object directly.

**Comment by takluyver** [comment]
This feature is now [documented under H5Pset_virtual](https://portal.hdfgroup.org/display/HDF5/H5P_SET_VIRTUAL). Thanks HDF group people!

**Comment by takluyver** [comment]
I think this one is reasonably straightforward: when creating a virtual dataset, check if each source filename matches the file it's being created in, and if so, use `'.'` as the filename.

Do we need an option to disable this? E.g. if you make a virtual dataset in one file, and then copy it to a second file, you may want the filenames to really refer to the original file.
