### ISSUE TITLE
Directly allow h5py datasets as "out" parameter of ufuncs (if possible)

### ISSUE THREAD

**Issue by s-m-e** [h5py/h5py#1553]
# Summary of the h5py configuration

h5py    2.10.0
HDF5    1.10.5
Python  3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 23:03:20) [GCC 7.3.0]
sys.platform    linux (4.15 x86 / Ubuntu 18.04)
numpy   1.18.1

# Bug / Missing Feature (?)

```python
import numpy as np
import h5py
a = np.arange(0, 16, dtype = 'float32').reshape(4, 4)
f = h5py.File('test.h5', mode = 'w')
b_ = np.zeros((4, 4), dtype = 'float32')
b = f.create_dataset('b', data = b_, chunks = (2, 2))
np.multiply(a, 2, out = b[:, :]) # does not change file on disk
np.multiply(a, 2, out = b) # TypeError: return arrays must be of ArrayType
f.close()
```

Some ufuncs (but not those from numpy itself) allow h5py datasets as out-parameters. I.e. the result of the computation is directly written to disk. numpy in fact rejects h5py arrays because they are not of "ArrayType". Could this be changed? I am not entirely sure given the nature of numpy's memory management.

**Comment by takluyver** [comment]
I don't think this is possible in general. I'm pretty sure that numpy functions write to their output as a block of memory; putting it through the abstraction layer would make them much slower.

I've been thinking about adding a memory-map method for contiguous (i.e. not chunked) datasets, which would give a numpy array. That would allow something like this:

```python
b = f.create_dataset('b', shape=(4, 4))  # Not using chunks
# Hypothetical:
with b.mmap() as b_arr:
    np.multiple(a, 2, out=b_arr)
```

**Comment by tacaswell** [comment]
It might also be interesting to look into using dask for this purpose.  I know it is already possible to back a dask array (lazily) with an h5py object, I am not sure if it will also manage writing it down the same way.

I am guessing that if you are in a situation where you want to write computation directly do disk it is because the data is large and you are going to eventually want to look at chunked versions of the algorithms (particularly because you _really_ want to do chunk aligned read / writes from the underlying dataset (being super careful about this is why pytables is fast)) and that is something that dask already has.

**Comment by takluyver** [comment]
I'm not aware that Dask can do anything clever with writing to HDF5 files - as far as I'm aware you have to collect all of the data in one process first, because you can't write an HDF5 file in parallel except by using MPI.

**Comment by tacaswell** [comment]
Ah, that is a very good point.

**Comment by takluyver** [comment]
I've opened #1607 with a more detailed description of my idea. I'm going to close this one, as I don't think the idea as stated is technically possible.
