### ISSUE TITLE
[Suggestion / New Feature?] Use of Built-in Method to Visualize the File Hierarchy

### ISSUE THREAD

**Issue by lfenzo** [h5py/h5py#1621]
Hello! 

I'm new to h5py and I don't know if this can cause any issues with the current implementation.

The idea of this suggestion is to add a built-in method capable of showing the file structure in a kind of 'file system tree' . I'm aware that there are ways to visualize it, such as [punx](https://punx.readthedocs.io/en/latest/source_code/h5tree.html), but I wonder if this visualization could be performed without the need of downloading and managing additional dedicated packages.

With that in mind, my suggestion would be something like:

Code:
```python
import h5py

with h5py.File('some/hf5/file.h5', 'r') as hdf_file:
    hdf_file.tree_view() # or 'file_structure_view()', 'structure_view()' or simply 'view()'...
```

Resulting in:
```
HDF5 File at /path/to/hdf5/file.h5

/
    dataset_0
    Group1
        dataset_1
        dataset_2
    Group2
        Group_3
            dataset_3
        dataset_4
```

Some possible parameters could be:

 `verbose`: specifying how much information is displayed in each node of the tree (e.g. show only keys, show keys and first elements of a dataset, show keys and attributes...);
 `file_output`: file to which the output can be redirected;
`indentation`: number of tabs to be used in file structure formatting

 * Operating System: Ubuntu 20.04 LTS
 * Python version: 3.7.7
 * Where Python was acquired: Mini Conda
```
python -c 'import h5py; print(h5py.version.info)'

h5py    2.10.0
HDF5    1.10.4
Python  3.7.7 (default, May  7 2020, 21:25:33) 
[GCC 7.3.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.19.1
```

**Comment by takluyver** [comment]
[h5glance](https://github.com/European-XFEL/h5glance) is our take on this - it's an extra package, but it's a fairly focused one, so maybe it's more palatable to install than something bigger like punx.

I tend to think this should be built on top of h5py, rather than in h5py. Deciding what information should be shown and how to present it nicely is surprisingly complicated - you've mentioned some of the complexities in your list of parameters. Different compromises may make sense for different scenarios. It's easier to say that h5py is not a visualisation tool, but you can use it to build visualisation tools, than to make an 'official' visualisation and start a lot of subjective arguments about what it should show and how. Building one visualisation into the library can also stifle the development of other tools.

**Comment by takluyver** [comment]
Maybe the docs should point to some useful viewer tools, though.
