### ISSUE TITLE
[Discuss] Do we need python format tool in this project?

### ISSUE THREAD

**Issue by dota17** [h5py/h5py#1648]
I found that there is no such tools like code style guide or format checking tool in this project, should we add them into the project?  So far, I've found two tools: [yapl](https://github.com/google/yapf) and [black](https://github.com/psf/black), but I don't know how do you think about them. 
If you have any idea about this, please discuss here 😄

**Comment by aragilar** [comment]
We used to have pylint and flake8 (which do the checking, not the autoformatting). I think I still have a branch with them sitting in my fork, but it will likely take a bunch of work to make them work cleanly on latest master.

I've used black before to format code where the formatting was all over the place, but I'm not a fan of its non-PEP8-ness.

I haven't played with yapf, nor [autopep8](https://github.com/google/yapf) (which is another tool). There are other tools which are more limited to what they do like [isort](https://pypi.org/project/isort/) or [pydocstyle](https://www.pydocstyle.org/en/stable/) and even more at https://github.com/PyCQA or https://gitlab.com/pycqa.

If we do end up reformatting things, we should set up a file to ignore those reformatting revisions (see https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revltrevgt, black has more details at https://github.com/psf/black#migrating-your-code-style-without-ruining-git-blame).

I think given none of the reformatters (as far as I know) can handle cython, we'd still have a fair bit on inconsistency, so I think we should only use a linter, not a reformatter, and I think having flake8/pylint or similar which checks for correctness (with formatting being a side thing) would be a better use of time than something which only does formatting (side note: given pylint was removed due to the repeated failing of PRs, if we end up using it, we should lock it, and use some other tool to keep pylint up to date).

**Comment by takluyver** [comment]
I'm generally -0.5 on strictly enforcing style guidelines with automatic tools. I know it's a trend for projects to do this, and I can see the attraction of making it completely consistent. But I don't find a bit of variation in style is actually a problem for reading code, and satisfying the style checker when you make a PR is an extra hurdle - both an annoyance for me, and an extra barrier for new contributors getting their code accepted.

Rigorously enforcing a style on an existing codebase also means reformatting much of the existing code, which has its own downsides - it would make `git blame` less useful, and potentially introduce unnecessary merge conflicts.

**Comment by dota17** [comment]
@aragilar @takluyver Thank you for your detailed reply. I think I've been convinced that we don't need format tools now.

**Comment by takluyver** [comment]
Thanks @dota17 - I'll close this now.
