### ISSUE TITLE
support for the ros3 driver

### ISSUE THREAD

**Issue by satra** [h5py/h5py#1712]
hdf5 created the ros3 driver with compile support for it in both 1.12.0 and 1.10.6. 

is there any timeline for h5py support for this?

**Comment by takluyver** [comment]
Does it work if you build HDF5 with that option and then build h5py yourself?

The HDF5 we bundle into prebuilt wheels for h5py is largely built with the default options. I'd hesitate to enable any non-default features without a proper understanding of what they are and why they're not enabled by default. But that shouldn't stop you using extra features if you build h5py on top of your own HDF5.

**Comment by satra** [comment]
> Does it work if you build HDF5 with that option and then build h5py yourself?

we are checking that out at the moment. will post it here.

unfortunately for our users, mostly neuroscientists, building is not a viable option. at least one path is via conda-forge which had it enabled but appears to not work. the hdf5group is helping debug that. 

https://github.com/conda-forge/hdf5-feedstock/issues/125

hopefully if this clears up at least that route may deliver a working h5py with this support built in.

however, we can definitely build it for any jupyterhub instance via a docker build.

**Comment by sirloon** [comment]
@satra I'm trying to achieve the same thing, I compiled hdf5 lib using `./configure --enable-ros3-vfd` then built h5py (branch 2.10.x), pointing to the HDF5 libs freshly compiled. I couldn't have this ros3 driver active though:

```
> h5py.registered_drivers()
frozenset({'core', 'family', 'fileobj', 'mpio', 'sec2', 'stdio'})
```

Explicit file open with drive='ros3' gives `ValueError: Unknown driver type "ros3"`...

Let me know how it goes and your end. Thanks!

**Comment by satra** [comment]
@takluyver - is there any guidance you can provide as to how we could add a new driver to h5py. is there an easy route through `register_driver`? i don't know what an `fapl` is. do we need to write some kind of shim, or can h5py introspect the built library directly?

**Comment by takluyver** [comment]
A `fapl` is a File Access Property List. HDF5 uses property lists extensively where we'd generally use default arguments in Python. To provide a specific file driver, we need to implement a function which takes a fapl and modifies it to specify the file driver to use. Like this for the mpio driver:

https://github.com/h5py/h5py/blob/27829cb3221dfe3e921eb745d69c47304327c0ae/h5py/_hl/files.py#L43-L50

That calls a method defined in Cython, which wraps the appropriate HDF5 function. What I'm not sure about is how to detect optional features of HDF5 at build time. Our current wrapping assumes that a given version of HDF5 always has the same functions, except for the MPI features. I don't want every optional feature in HDF5 to need a corresponding option in h5py as well.

It should be possible, I think, to do something like `#ifdef H5_HAVE_ROS3_VFD`, so that feature is automatically wrapped if present. But I don't know exactly how to write that in Cython code. If we can work that out, then we just need to integrate it with our [script that generates the bindings](https://github.com/h5py/h5py/blob/master/api_gen.py).

**Comment by satra** [comment]
thank you @takluyver - we will look into it and post back here.

**Comment by takluyver** [comment]
It looks like you did this in #1755. Could I ask you to [write a release note](https://docs.h5py.org/en/stable/contributing.html#write-a-release-note) for it? Then I guess we can close this issue.
