### ISSUE TITLE
Any possibility to write to a file object that doesn't allow append?

### ISSUE THREAD

**Issue by rainwoodman** [h5py/h5py#1720]
To assist reproducing bugs, please include the following:
 * Operating System (e.g. Windows 10, MacOS 10.11, Ubuntu 16.04.2 LTS, CentOS 7)
   Linux
 * Python version (e.g. 2.7, 3.5)
3.7
 * Where Python was acquired (e.g. system Python on MacOS or Linux, Anaconda on
   Windows)
Customized.
 * h5py version (e.g. 2.6)
2.10
 * HDF5 version (e.g. 1.8.17)
1.8
 * The full traceback/stack trace shown (if it appears)

We are looking into ways to access HDF5 files hosted by an API-side file system that only allows appending to a file via h5py's File object support.

Reading works well, but for writing, currently we are stuck at the error when the HDF5 issues a seek to the File object, because the file system doesn't allow seeking to a location other than the end of the file.

Any suggestions whether random-write is a strict requirement for HDF5?

For example, is there a special mode/driver of HDF5 that avoids rewriting already committed/written parts of a file?
I looked at HDF5 documentation and there doesn't appear to be any reference to such a mode, but I may have missed it because I am not very familiar with the internals of HDF5.

**Comment by takluyver** [comment]
The only thing I can think of like that is to store the data in memory until the 'file' is closed, and then write it out afterwards. The 'core' driver with the `backing_store` option can do this, for instance. Of course, that only works if your data fits in memory. With HDF5 1.12 it might be possible to use the new virtual object layer to do something similar at the level of objects rather than files, if you have a lot of datasets but each one is fairly small.

You might want to try asking HDF group (either on the [HDF Forum](https://forum.hdfgroup.org/) or help@hdfgroup.org).

**Comment by takluyver** [comment]
Closing as I don't think there's anything concrete for h5py to do here. There might be other ways to do what you want, but as far as I know, HDF5 requires that the file abstraction allows non-sequential access.
