### ISSUE TITLE
Wheel support for Windows 32 bit

### ISSUE THREAD

**Issue by yuxuanzhuang** [h5py/h5py#1753]
Hi! I noticed the latest 3.0 version has dropped the PyPI wheel support for Windows 32 bit. I am just wondering if such support has been deprecated, or if you plan to include it again in the future. Thanks!

**Comment by skoudoro** [comment]
+1, our 32bits wheels (DIPY) are failing as you can see [here](https://github.com/MacPython/dipy-wheels/pull/7/checks?check_run_id=1502330368#step:10:407) and the package fails to build under 32bits.

Is it deprecated for 3.0.0+ or should we expect some compatibilities?

Thank you h5py for the feedback and this nice project!

**Comment by franzhaas** [comment]
Any plans to provide 32bit windows wheels in the future? any news here?

**Comment by neutrinoceros** [comment]
Windows wheels have been built targeting the `amd64` arch exclusively since #1674 (h5py 3.0.0). Setting up win32 wheels again seems technically possible (it is certainly supported by cibuildwheel), but may prove challenging.
However, my impression is that Microsoft discontinued their 32bit arch so I'm not sure it is worth the effort to reintroduce support on our side. If anyone wants to give it a try however we can certainly have a look.

**Comment by tacaswell** [comment]
I am going to close this as I agree it is unlikely we are going to build win32 wheels again.

I also want to stress that not providing wheels does not mean that h5py does not work on a given platfrom, it just means we are not building the wheels (Wheels (from any project) should always be considered "best effort" and a convenience for users, see https://pypackaging-native.github.io for a long discussion of limitations of wheels).

If we are not actively testing a platform it is possible that some incompatibilities have crept in, but we will happily review/merge PRs fixing support on platforms that do not readily have free CI available to open source projects.
