### ISSUE TITLE
Strings not read correctly?

### ISSUE THREAD

**Issue by tdegeus** [h5py/h5py#1769]
On my Linux system since recently I have to do the following to use a list of strings:
```python
files = [file.decode('UTF-8') for file in data['/files'][...]]]
```

This is my system:
```
h5py    3.1.0
HDF5    1.10.6
Python  3.8.6 | packaged by conda-forge | (default, Nov 27 2020, 19:31:52)
[GCC 9.3.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.19.4
cython (built with) 0.29.21
numpy (built against) 1.16.5
HDF5 (built against) 1.10.6
```

**Comment by takluyver** [comment]
The string interfaces changed in 3.0 - [release notes](https://docs.h5py.org/en/stable/whatsnew/3.0.html)). You can use `data['/files'].asstr()[...]` to read them as str objects - this is essentially a convenient shortcut for the list comprehension you've written.

**Comment by tdegeus** [comment]
Great, thanks! I couldn't find it in the release notes though, but I did find it [here](https://docs.h5py.org/en/stable/strings.html).

I find the API a bit confusing, as in, I'm reading a *list of* strings, not a `string`. I find that the API suggests a bit that I'm concatenating everything into a single string object.

Is there now also a better way to write a list of strings? I am currently using a support function:
```python
def create_dataset_str(h5py_file, path, stringlist):
    data = np.array(stringlist, dtype=object)
    string_dt = h5py.special_dtype(vlen=str)
    h5py_file.create_dataset(path, data=data, dtype=string_dt)
```
But I would like to do
```python
h5py_file[path] = stringlist
````

**Comment by takluyver** [comment]
This is the relevant release note, for reference - under 'Breaking changes & deprecations':

> Variable-length UTF-8 strings in datasets are now read as bytes objects instead of str by default, for consistency with other kinds of strings. See [Strings in HDF5](https://docs.h5py.org/en/stable/strings.html) for more details.

Yeah, sorry, that is a bit unfortunate. I was focused on the distinction between str & bytes when I named it, and I didn't think about single vs multiple. It also roughly parallels `astype`.

> But I would like to do
>
>     h5py_file[path] = stringlist

Does that not work? It should do, and `f['data'] = ['a', 'b', 'cde']` works for me.

**Comment by tdegeus** [comment]
Sorry I didn't confirm earlier. Writing works perfectly fine, and reading indeed also with `data['key'].asstr()[...]`

**Comment by moi90** [comment]
It is a bit counter-intuitive to write something as string with an encoding and reading it back as bytes. I my opinion, it would be better if h5py would see that this is utf-8-encoded data and therefore directly provide a string.

**Comment by takluyver** [comment]
There's always going to be some awkwardness, because Python & HDF5 view strings in quite different ways, so you can't easily map between them.

In this case, we wanted to make fixed-size and variable-size strings behave more similarly, because they're variants of the same HDF5 type. Fixed-size strings are a fixed number of bytes, so the efficient way to read them is into a numpy bytes array (like `dtype('S5')`). So reading variable length strings into an array of bytes objects makes them more similar.

HDF5 also doesn't ensure that data tagged UTF-8 is actually UTF-8. It's easier to deal with that if the basic API just gives you the data that's in the file (i.e. bytes) rather than trying to decode it.

**Comment by tdegeus** [comment]
I'm reopening this issue because there is a real bug in the sense that the API is not consistent. Support that I write
```python
with h5py.File('foo.h5', 'w') as data:
    data['foo'] = ['abc', 'def', 'ghi']
    data['foo'].attrs['bar'] = ['abc', 'def', 'ghi']
```
I currently have to read **differently**
```python
with h5py.File('foo.h5', 'r') as data:
    a = data['foo'].asstr()[...]
    b = data['foo'].attrs['bar'][...]
```
Replacing the second line in 
```python
    b = data['foo'].attrs['bar'].asstr()[...]
```
results in
```
'numpy.ndarray' object has no attribute 'asstr'
```

----------

Now, a personal remark is that I find having to add `asstr()` everywhere quite annoying. But it is true that I only read and write variable sized strings, and only few. Presumably others might be able to benefit from the new API, but this I cannot judge as it is outside my scope of use.

**Comment by aragilar** [comment]
Fundamentally datasets and attributes are not the same thing, both at the HDF5 format level and the h5py level, and there will always be differences between the two. Accessing an attribute gives you back the python object directly if its a scalar, or a numpy ndarray otherwise (so you must read the whole attribute), whereas accessing a dataset gives you back a `Dataset` object you can slice/convert or perform any other operations listed at https://docs.h5py.org/en/stable/high/dataset.html#h5py.Dataset on. Because of this, attributes perform the decoding (though you need to watch out for mojibake), whereas datasets allow for more precise and controlled handling of how the strings decoded.

The other thing that is likely tripping you up is the use of lists—while h5py does allow their use when writing, you need to remember that h5py always works with numpy ndarrays, and so if the rest of your code expects lists (or strings), I would write a wrapper around h5py which handles this, and keep it separate from your ["business logic"](https://en.wikipedia.org/wiki/Business_logic) (I did this for my code at https://github.com/h5preserve/h5preserve, but there are other wrappers mentioned in https://github.com/h5py/h5py/pull/1626).

**Comment by tdegeus** [comment]
Thanks @aragilar , that clarifies things. However, my personal opinion (that is not hindered by having any use case for fixed-sized strings), is that even if attributes may be 'simpler' it still feels inconsistent that for a dataset one does not directly obtain a NumPy-array of variable-length strings, while one *does* for attributes.

**Comment by takluyver** [comment]
IMO, *something* is always going to feel inconsistent: Python & HDF5 have quite different concepts of strings, which h5py has to try to line up. We can pick different things to make awkward, but there's no option that's going to be ideal for every use case.

I appreciate that for many use cases it would be convenient to turn variable length UTF-8 strings into Python str objects. We decided against that for two reasons:

1. Bytes represent the real data in the file. HDF5 doesn't guarantee that data marked as UTF-8 is actually UTF-8, and if you ever have to deal with a situation where it's not, it's easier to start from the data in the file than h5py's attempt to interpret it.
2. Fixed-length and variable length strings are variants of the same type in HDF5, so we wanted to read them in a similar way. The most efficient way to read fixed-length strings is into a numpy bytes array (e.g. `dtype('S5')`), because fixed length means fixed number of bytes. Reading vlen strings as object arrays of bytes gives the most similar behaviour.

For attributes, we made a different decision, because attributes fit naturally in use cases where convenience is more important.

We redesigned how strings work for h5py 3.0 (see #1338). Given that any change means breaking the API, and I don't think we can ever avoid inconsistencies entirely, I think there's a very high bar to making any changes now.

**Comment by moi90** [comment]
I would expect that I read a string if I wrote a string. The defaults should be swapped in my opinion: Always return a string if an encoding is given. An exception is thrown if the data is marked as utf8 but is in fact something else. If the user really wanted bytes, they could use `asbytes`.

**Comment by aragilar** [comment]
@moi90 h5py has no way to know if the encoding in the file can be trusted or not (and the encoding is always there), any file h5py may read could come from any of the implementations listed at https://en.wikipedia.org/wiki/Hierarchical_Data_Format#Third-party_bindings (or the main HDF5 library, which itself never ensures that the encoding information is correct). Nor does it know who wrote the file, nor the original type passed to h5py (if h5py was the writer of the file). To avoid needing to manually wrap strings with `string_dtype` and `vlen_dtype`, h5py does accept lists of python strings as a convenience (rather than throwing an exception, as it has done in the past), but the first thing it does is convert them to numpy ndarrays (which are what are given back to the user when being read back).

Given that currently numpy (there have been discussions on their mailing lists and GitHub, but that requires major changes to dtypes) lacks a way to store "strings" (i.e. something that behaves like a python string) compatible with the way HDF5 stored strings, h5py is stuck in the middle of all three (Python, numpy and HDF5, all of which have different string models), and tries to provide an API which works for all use cases (which may not be ideal for all users, but does not prevent anyone from using it). I don't see h5py changing how strings work unless there was a major change to numpy (if that ever happens), and even then, we would need consider how any changes would affect backwards compatibility.

**Comment by moi90** [comment]
OK, I see. Thanks for the explanation!

**Comment by tdegeus** [comment]
Thanks @aragilar ! Let's close then.

**Comment by Grazeraven41** [comment]
I struggled with that problem and devised a remedy https://docilecompetence.github.io/mapbox-gl-draw/
