### ISSUE TITLE
How to include jpg into h5?

### ISSUE THREAD

**Issue by santimirandarp** [h5py/h5py#1787]
I've read the docs as well as I could but I can't find how to get my jpg files into an h5 dataset. Wrote this:
```
import glob, h5py
import numpy as np
cats = "images/raw/cats/*"
out = "images/clean/train.h5"
def convert_file(input_dir, output_file):

    files = glob.glob(input_dir)
    numOfFiles = len(files)

    h5File = h5py.File(output_file, "w")
    dt = h5py.special_dtype(vlen=np.dtype('uint8'))
    features = h5File.create_dataset('features_train', (100, ), dtype=dt)
    labels = h5File.create_dataset('labels_train', (100, ), dtype="i")
    np.append(labels, np.arange(numOfFiles))
    for f in files:
        fin = open(f, 'rb')
        binary_data = fin.read()
        filename = f.split('.')[0]
        basename = filename.split('/')[-1]
        np.append(features, np.frombuffer(binary_data, dtype='uint8'))
    print("done")
    return 1
convert_file(cats, out)
```

Would you please point me in any good direction?

**Comment by aragilar** [comment]
@santimirandarp I think this would be better asked on the support forum at https://forum.hdfgroup.org/c/hdf-tools/h5py rather than as an issue. I'm guessing based on the context though this is related to machine learning, in which case the best place to ask would be the user support for whichever machine learning library you are using, as they can tell you exactly how you need to save your jpgs.
