### ISSUE TITLE
How do I open and read data from the same slot with a large number of files in read-only mode

### ISSUE THREAD

**Issue by weir12** [h5py/h5py#1806]
1.  Environment
   * CentOS 7
   * Python 3.6
   * Anaconda
   * h5py 2.10.0
   * HDF5 1.10.6
 2.  Issue

  -  Input: a list of hdf5 files [path_to_file_1,path_to_file_2...path_to_file_N]
  
  - What i wanna do : Open them and read the data from the specified slot and transfer them to memory
  - Trouble: Serial reading of data is too slow, multi-threading and coroutines do not work(even more slowly), the only valid is multi-process(but the cost is  too much for OS )

Can anyone provide some optimization ideas? 
I appreciate any help.

**Comment by vasole** [comment]
h5py 3.x should be releasing the GIL more often and multi-threading might help in that case.

**Comment by takluyver** [comment]
Releasing the GIL is unfortunately unlikely to help, because HDF5 has its own global lock, so only one thread can be in HDF5 calls at a time. As far as I know, using multiple processes is a requirement to read HDF5 data in parallel.

**Comment by weir12** [comment]
> Releasing the GIL is unfortunately unlikely to help, because HDF5 has its own global lock, so only one thread can be in HDF5 calls at a time. As far as I know, using multiple processes is a requirement to read HDF5 data in parallel.

`export HDF5_USE_FILE_LOCKING=FALSE` 
So setting environment variables like this is not helpful either.Right?

**Comment by takluyver** [comment]
Right. File locking means locking a file when it's open for writing, so another process can't open the same file. That's separate from the lock that prevents two threads in the same process from using HDF5 at the same time.

**Comment by takluyver** [comment]
So I think this comes down to 'how to reduce the overhead of using multiple processes'. That's not really specific to h5py, but a few ideas:

- If you've got a lot of files, make sure you're not starting a new process for each file. A `multiprocessing.Pool` or similar will do the right thing.
- On Unix, forking can start worker processes faster than spawning, though it has some traps for the unwary. Multiprocessing will use forking by default on Unix systems (except Macs).
- If each file has a lot of data, and each file can be processed independently, you might want to do the processing in the worker processes, to avoid transferring the data back to the main process.
- If you do need to read a lot of data in each worker and then use it all in the main process, it may be more efficient to load it into shared memory, with a package like [sharedmem](https://github.com/rainwoodman/sharedmem), rather than letting multiprocessing pickle it to send pack to the main process. h5py's [Dataset.read_direct()](https://docs.h5py.org/en/stable/high/dataset.html#h5py.Dataset.read_direct) method can help you avoid allocating and copying memory unnecessarily.

I'm going to close this as there's nothing really to solve for h5py. It's a known limitation that HDF5 can't really use multiple threads, even when you're accessing completely separate files.
