### ISSUE TITLE
Handling corrupt data after crash

### ISSUE THREAD

**Issue by HonakerM** [h5py/h5py#1807]
Hello! So I have a system where my program is using an h5py File as a buffer. I want it to be able to recover the buffer after a crash. However sometimes when reopening the file I get a `OSError: Unable to open file (truncated file: eof = 2288632, sblock->base_addr = 0, stored_eof = 2501624) `  what is the cause of this error? How can I avoid it?

This is on h5py version 3.1.0

[Edit] I tried opening the file in swmr mode but while the data is good I get a `file is already open for write/SWMR write (may use <h5clear file> to clear file consistency flag)`

**Comment by HonakerM** [comment]
I also started running into an interesting issue. I created a dataset using the following commands
```
import h5py
file = h5py.File('test.h5df','w',swmr=True, libver='latest')
dset = file.create_dataset("data",shape=(10,4))
file.flush()
```
I then terminated the session to simulate a crash. When I went to reopen the file I got the following errors
```
>>> old_file= h5py.File('test.h5df','r',swmr=True, libver='latest')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mchonaker/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 427, in __init__
    swmr=swmr)
  File "/home/mchonaker/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 190, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
OSError: Unable to open file (file is not already open for SWMR writing)
```
I then tried to open the file in write mode and got the following error:
```
>>> old_file= h5py.File('test.h5df','r+',swmr=True, libver='latest')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mchonaker/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 427, in __init__
    swmr=swmr)
  File "/home/mchonaker/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 192, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
OSError: Unable to open file (file is already open for write/SWMR write (may use <h5clear file> to clear file consistency flags))
```

What is the cause of this? The file thinks both someone is writing and no one is writing.

**Comment by HonakerM** [comment]
It seems like not using `libver='latest'` seems to fix the problem,

**Comment by HonakerM** [comment]
Upon further investigation it seems that sometimes the file is correctly read and other times I get a `truncated file` error. What could be the cause of this?

**Comment by vasole** [comment]
If the file was not properly closed, there might be some consistency flags in the header.

Have you tried to use h5clear?

https://support.hdfgroup.org/HDF5/doc/RM/Tools.html

**Comment by HonakerM** [comment]
@vasole I'm trying to allow for my system to autorecover from a crash where there's a chance the file couldn't be closed correctly. I thought when using swmr mode the data was always in a valid state? My idea would be to open the file as read only then copy its contents to a new hdf5 file with write access and then continue using that

**Comment by vasole** [comment]
I do not know how SWMR works internally. In your case I would copy the original file and try h5clear on the copy. Nothing worse can arrive by trying that.

**Comment by HonakerM** [comment]
Does h5py support h5clear on its own? Or do I have to execute an external command? Thank you for your assistance

**Comment by vasole** [comment]
The command line HDF5 tools (h5clear, h5repack,...) are provided by the HDF5 Group.

**Comment by takluyver** [comment]
Note that `h5py.File('test.h5df','w',swmr=True)` doesn't put the file into SWMR mode. This is confusing, but the [reference docs](https://docs.h5py.org/en/stable/high/file.html#reference) say:

> swmr – If True open the file in single-writer-multiple-reader mode. **Only used when mode=”r”.**

We should probably error/warn if that's passed with another mode.

To use SWMR write mode you need to set `f.swmr_mode = True`.

**Comment by takluyver** [comment]
I think I've understood what's going on.

> The file thinks both someone is writing and no one is writing.

The error messages `not already open for SWMR writing` and `is already open for write/SWMR write` are both compatible with the file having been opened in non-SWMR write mode, and not properly closed. This is consistent with the code you showed, because `File(..., swmr=True)` is used for SWMR *read* mode, not write mode. I've opened a PR to add a warning when `swmr=True` is being ignored.

> It seems like not using libver='latest' seems to fix the problem,

By default, HDF5 prefers older versions of its file format, for maximum compatibility. The 'file consistency flags', which record inside the file whether it's open for write & SWMR write, are added in a newer version of the file format (specifically, [superblock](https://support.hdfgroup.org/HDF5/doc/H5.format.html#Superblock) v3).

So when you use `libver='latest'`, you get a deterministic error that the file is open for writing, based on the flags. If you know that the writer has crashed, I think `h5clear -s <file>` should reset the flags and get past that error.

> sometimes the file is correctly read and other times I get the following error... Unable to open file (truncated file

At a guess, sometimes HDF5 has written a valid file before the process crashes, and sometimes it hasn't. It looks like `f.flush()` ought to ensure the file is written out, but I don't know if that's actually guaranteed. Using SWMR write mode (`f.swmr_mode = True`) might make it easier to ensure a valid file on disk before it's closed, but I haven't used SWMR myself.

If you get the truncated file errors, the `--increment` option to `h5clear` *might* get past them and let you read some data. But I imagine you might also get garbage, or if you're unlucky reading an invalid file could even crash your process. If the error says `eof = 96` (i.e. the file is 96 bytes), there's almost certainly no useful data to be recovered.

**Comment by takluyver** [comment]
I'm going to close this as I believe my comment above covers what's going on and what you might be able to try. You can keep using the comments here if you want.
