### ISSUE TITLE
Using a python file stream in append mode?

### ISSUE THREAD

**Issue by edswangren** [h5py/h5py#1838]
* Windows 10
 * Python 3.6.8
 * Anaconda
 * h5py version 2.9
 * HDF5 version 1.10.4
 * The full traceback/stack trace shown (if it appears)

I'd like to wrap our serialization in an interface which accepts streams instead of paths, but I'm hung up in the general case (writing a file to disk).  We write to HDF files iteratively, so we always open in append mode

`with h5py.File(path, 'a') as f:`

In trying to use a stream, I ran into (an obvious) issue. In memory works great, but for my typical use case, and I imaging some future ones, I end up with a corrupt file.

```
with open(R"C:\tmp\test.h5", "ab+") as stream:
    with h5py.File(stream, "a") as f:
        g = f.require_group("1")
        g.create_dataset("test2", data=[2,3,5], dtype="int32")
```

Now, I can understand that you likely have optimizations for your append mode which are more difficult to implement when taking a random stream as an argument, so my question really is only whether or not I can accopmplish what I'm after here. I'd prefer to avoid two differing API's if possible, but I can't find anything that explicitly tells me this won't work.

**Comment by takluyver** [comment]
I'm not quite sure what you mean by a stream, but HDF5 does assume that the file is random access, so it won't be able to write in a streaming fashion to a socket or a pipe.

Passing in a Python file object is more complex - the C code has to call back to Python to read & write - and as you've found, it makes for more confusing failures. I think h5py's `'a'` mode is meant to be roughly equivalent to `open(..., 'a')` in meaning - add to this file if it exists, create it otherwise - but it's completely different in what it actually does.

Within HDF5, there are two distinct functions: *open* an existing file (h5py modes r/r+) or *create* a new one (modes w/w-/x). The 'a' mode simply tries open first and then falls back to create. To work with a Python file-like object, I think you need to lift this distinction into your own code - separate handling for starting a new file and adding to an existing one.

**Comment by edswangren** [comment]
Thanks. I've opted for a simpler approach and it's nice to get some 'official' feedback. Appreciate it.

**Comment by takluyver** [comment]
Closing as I think there's nothing more to be done here - if I've misunderstood, let me know. :slightly_smiling_face:
