### ISSUE TITLE
Test failures with ROS3 enabled

### ISSUE THREAD

**Issue by takluyver** [h5py/h5py#1843]
@satra, can you take a look?

Conda-forge tried to update to 3.2 (https://github.com/conda-forge/h5py-feedstock/pull/86) but got test failures. It appears that their HDF5 has the ROS3 driver enabled. All the tracebacks I've spotted end here:

```
    @property
    @with_phil
    def driver(self):
        """Low-level HDF5 file driver used to open file"""
        drivers = {h5fd.SEC2: 'sec2',
                   h5fd.STDIO: 'stdio',
                   h5fd.CORE: 'core',
                   h5fd.FAMILY: 'family',
                   h5fd.WINDOWS: 'windows',
                   h5fd.MPIO: 'mpio',
                   h5fd.MPIPOSIX: 'mpiposix',
                   h5fd.fileobj_driver: 'fileobj'}
        if ros3:
>           drivers[h5fd.ROS3] = 'ros3'
E           AttributeError: module 'h5py.h5fd' has no attribute 'ROS3'
```

**Comment by satra** [comment]
@takluyver -  i think this commit is the culprit: https://github.com/h5py/h5py/pull/1755/commits/1cbde4c87067b2e28092e0c48e2c921af28c7c48

when i keep that variable the h5py tests do not pass, because the driver used in h5py testing does not have `ROS3` enabled. 

sending a PR to recreate the error to see where it breaks.
