### ISSUE TITLE
Management of HDF5 dataspace identifiers for virtual dataset layouts

### ISSUE THREAD

**Issue by ajelenak** [h5py/h5py#1865]
This issue was discovered when running the following code:
```python
raw_file = "rawfile.h5"

layout = h5py.VirtualLayout(shape=(16_000_000,), dtype='i4')
vsource = h5py.VirtualSource(raw_file, 'data', shape=(2,))

for i in range(8_000_000):
    layout[2*i:2*i+1] = vsource[0:1]
```
The `layout.sources` list will hold 16 million *active* (created but not yet closed) HDF5 dataspace identifiers after the *for* loop. The HDF5 library requires huge amounts of memory for these many dataspace identifiers, on the order of several tens of gigabytes.

Until this issue is addressed on the library side, would it be possible to modify h5py code to reduce the number of active dataspace identifiers for virtual dataset layouts? One possibility could be to defer creating dataspace identifiers until having to use them, like before the `PropDCID.set_virtual()` call in the [`make_new_virtual_dset()`](https://github.com/h5py/h5py/blob/cff8537cc74a4897e2c0dc523309be17bec06dd4/h5py/_hl/dataset.py#L159-L160) function. The `VirtualSource.__getitem__()` and `VirtualLayout.__setitem__()` methods would then need to store the required information only as Python objects that do not include any low-level h5py objects that represent HDF5 identifiers.

Summary of the h5py configuration:
```
h5py    3.2.1
HDF5    1.12.0
Python  3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:20) 
[Clang 11.0.1 ]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   1.20.1
cython (built with) 0.29.22
numpy (built against) 1.19.3
HDF5 (built against) 1.12.0
```

cc: @bmribler @bljhdf

**Comment by takluyver** [comment]
Have you tried this with the low-level API, or with the HDF5 C API? Looking at the code, I think HDF5 does essentially the same thing - storing a list containing dataspaces in the property list as you build a virtual dataset ([see this code](https://github.com/HDFGroup/hdf5/blob/e0eb5c6e1dbf527db240faa0f398617577ec783f/src/H5Pdcpl.c#L2305-L2343)).

My impression is that virtual datasets are designed to be made from hundreds or a few thousand mappings, not millions.

**Comment by ajelenak** [comment]
Yes, I did create a simple C program that mimics HDF5 API operations of the Python code and used it to assess memory use growth with increasing number of active dataspace identifiers.

You are correct that the millions of mappings are certainly stretching the virtual dataset concept beyond extreme. And not accumulating dataspace identifiers in `VirtualLayout` would not solve this problem because the `H5Pset_virtual()` code you highlighted makes a copy of its input dataspace identifiers anyway. However, not having dataspace identifiers in `VirtualLayout` would make it possible that memory consumption goes toward dataspace identifiers created in the `H5Pset_virtual()` function only.

**Comment by takluyver** [comment]
Maybe the way to address this is for `VirtualLayout` to create and update a dataset creation property list, calling `dcpl.set_virtual()` as you do each `layout[ s ] =` mapping. That means no double memory use as they're copied from a Python list into an HDF5 property list, while also getting the checks HDF5 does earlier - e.g. this could supersede my PR #1863.

**Comment by ajelenak** [comment]
Sounds like a plan. How to proceed? I start from your PR?

**Comment by takluyver** [comment]
That PR is arguably redundant if we're calling `dcpl.set_virtual()` immediately, because HDF5 will check the same thing. Although we can probably give a more helpful error message, but I'm not sure it's worth checking it just for that.

So I'd start from master. I'm happy to have a go at this if you like, but I'm also happy to review it if you'd like to make the changes.

**Comment by ajelenak** [comment]
Alright, let me start and then we'll see how much from your PR can be included.

**Comment by ajelenak** [comment]
Moving `dcpl.set_virtual()` to `VirtualLayout.__setitem__()` prevents doing this:
https://github.com/h5py/h5py/blob/0589e69e48eaf4c28ba8fab5b5020f54f7f08089/h5py/_hl/group.py#L169-L178
because the `VirtualLayout` class does not know the file name of a future virtual dataset.

One option is to add a new method to the `File` class that would produce a `VirtualLayout` object with the file name information. This can be made backward compatible by adding something like `filename=None` to `VirtualLayout.__init__()`. Would something like this be acceptable?

**Comment by takluyver** [comment]
Oh, that's unfortunate. :-( Adding an optional filename doesn't really make it backwards compatible, because existing code expects the translation to be done when it's added to the destination file, and that would stop working.

I'll try to think what can be done about this, because I do like the idea of building a property list in VirtualLayout.

**Comment by ajelenak** [comment]
Here's in more detail what I was thinking:

1. Move the file name grooming code I highlighted into `VirtualLayout.__setitem__()`.
2. Add `VirtualLayout.__init__(..., filename=None)`.
3. No file name grooming in `VirtualLayout.__setitem__()` when `filename=None`.
4. Add a new method to `File` or `Group` that can return a `VirtualLayout` object where the `filename` argument is set. This then triggers file name grooming in that object's `__setitem__()`.

**Comment by takluyver** [comment]
That's what I had understood. :slightly_smiling_face: But existing code which calls `VirtualLayout()` wouldn't receive the filename translation that it currently gets in h5py 3.2, so it would break for people who want that (and people do, it was added as a specific feature).

**Comment by ajelenak** [comment]
Then how about storing in `VDSmap` the mapping information without HDF5 dataspace identifiers? If its possible to create those identifiers from that `VDSmap` info in the `make_new_virtual_dset()` then `dcpl.set_virtual()` can stay where it is now.

**Comment by takluyver** [comment]
We'd still have to store the information needed to make the dataspaces & selections, which I doubt is much lighter than the dataspace objects themselves. And delaying more of the operations makes it harder to do sanity checking where the inputs are given - I like the idea of calling `set_virtual` earlier because it allows for more up-front sanity checks.

How about this: `VirtualLayout` contains a DCPL and calls `dcpl.set_virtual()` as you make each mapping. If it has the filename from the start, `create_virtual_dataset()` uses that dcpl directly to create the dataset. If it didn't, then `create_virtual_dataset()` extracts the mappings with `get_virtual_{vspace, filename, dsetname, srcspace}`, making the filename adjustment and adding each mapping to a new DCPL. It might be a bit slower than the existing code, but probably not much, and we can use Cython to speed it up if necessary.

After a while, we could then deprecate and remove the late option for filename translation, simplifying the code to always use the DCPL built by VirtualLayout.

Bonus: we could use a context manager API for making virtual datasets:

```python
with f.build_virtual_dataset('alldata', (1000, 10), np.int64) as layout:
    layout[:100] = VirtualSource(...)
    ...
```

**Comment by takluyver** [comment]
I've had a go at what I proposed above in #1905.
