### ISSUE TITLE
undefined symbol: H5Pset_fapl_ros3

### ISSUE THREAD

**Issue by Zethson** [h5py/h5py#1880]
To assist reproducing bugs, please include the following:
 * Operating System: Ubuntu 18 Docker
 * Python version: 3.8
 * Where Python was acquired: Conda
 * h5py version (e.g. 2.6): results in error
 * HDF5 version (e.g. 1.8.17): 1.10.6
 * The full traceback/stack trace shown (if it appears)

Dear everyone,

I am using a Docker container based on `jupyter/minimal-notebook:latest`. It already has a miniconda with Python 3.
Next, I installed h5py (was a dependency of something else). However, when attempting to use it I get:

```
(sc-analysis) jovyan@7171d029a008:~$ python -c 'import h5py; print(h5py.version.info)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/sc-analysis/lib/python3.8/site-packages/h5py/__init__.py", line 33, in <module>
    from . import version
  File "/opt/conda/envs/sc-analysis/lib/python3.8/site-packages/h5py/version.py", line 15, in <module>
    from . import h5 as _h5
  File "h5py/h5.pyx", line 1, in init h5py.h5
ImportError: /opt/conda/envs/sc-analysis/lib/python3.8/site-packages/h5py/defs.cpython-38-x86_64-linux-gnu.so: undefined symbol: H5Pset_fapl_ros3
```

Do you have any idea? I can share the full container if required.
Thanks.

**Comment by Zethson** [comment]
Update: This issue only occurs when installing the package with mamba (https://github.com/mamba-org/mamba), but not with Conda. 
Feel free to close if you think that it's not your responsibility.

**Comment by aragilar** [comment]
The error is due to the HDF5 library being used not matching the configuration h5py was built with. This sounds like whichever source(s) of libraries mamba is using, they're not consistent (which is a mamba problem).

**Comment by batterseapower** [comment]
I just hit this too (I'm also using Mamba). I worked around the issue for now by forcing `h5py<3.2` in my `environment.yml`.

**Comment by Zethson** [comment]
@batterseapower guess we should report this to Mamba. Their resolver clearly does something very wrong.

**Comment by hugobuddel** [comment]
Ran into this too, using mamba. But I have not been able to reproduce it. This works fine:
```
conda create -y -n h5pymambatest mamba
conda activate h5pymambatest
mamba install -y h5py
python -c 'import h5py; print(h5py.version.info)'
```
yielding
```
Summary of the h5py configuration
---------------------------------

h5py    3.2.1
HDF5    1.10.6
Python  3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:46) 
[GCC 9.3.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.20.2
cython (built with) 0.29.23
numpy (built against) 1.19.5
HDF5 (built against) 1.10.6
```
So I wouldn't know how to create a issue for mamba..

**Comment by hugobuddel** [comment]
I'm trying to figure out what the mamba dependency resolver got wrong in order to make sure the problem is on their end. The other possibility is that the h5py package is a too lax in defining the dependencies it needs.

Both mamba and conda select this h5py package:  [linux-64/h5py-3.2.1-nompi_py39h98ba4bc_100.tar.bz2](https://anaconda.org/conda-forge/h5py/files/modal/info/6079fab1c0b1dfaea0084334)
```
None
Uploaded 	Fri Apr 16 20:59:27 2021
md5 checksum 	e25db91699a5a23afe6fa7581c3162ae
arch 	x86_64
build 	nompi_py39h98ba4bc_100
build_number 	100
depends 	cached-property, hdf5 >=1.10.6,<1.10.7.0a0, libgcc-ng >=9.3.0, numpy >=1.19.5,<2.0a0, python >=3.9,<3.10.0a0, python_abi 3.9.* *_cp39
license 	BSD-3-Clause
machine 	x86_64
operatingsystem 	linux
platform 	linux
subdir 	linux-64
target-triplet 	x86_64-any-linux
timestamp 	1618606720811
```
conda (and mamba when working correctly) select [linux-64/hdf5-1.10.6-nompi_h6a2412b_1114.tar.bz2](https://anaconda.org/conda-forge/hdf5/files/modal/info/5ff8e6e1062dd686761f93ea) as dependency:
```
None
Uploaded 	Fri Jan 8 23:12:30 2021
md5 checksum 	0a2984b78f51148d7ff6219abe73509e
arch 	x86_64
build 	nompi_h6a2412b_1114
build_number 	1114
depends 	libcurl >=7.71.1,<8.0a0, libgcc-ng >=9.3.0, libgfortran-ng, libgfortran5 >=9.3.0, libstdcxx-ng >=9.3.0, openssl >=1.1.1i,<1.1.2a, zlib >=1.2.11,<1.3.0a0
has_prefix 	True
license 	LicenseRef-HDF5
license_family 	BSD
machine 	x86_64
operatingsystem 	linux
platform 	linux
subdir 	linux-64
target-triplet 	x86_64-any-linux
timestamp 	1610147411581
```

When not functioning properly, mamba selects [linux-64/hdf5-1.10.6-nompi_h3c11f04_101.tar.bz2](https://anaconda.org/conda-forge/hdf5/files/modal/info/5f240e7978705809fc4e00fb):
```
None
Uploaded 	Fri Jul 31 12:28:40 2020
md5 checksum 	9f1ccc4d36edf8ea15ce19f52cf6d601
arch 	x86_64
build 	nompi_h3c11f04_101
build_number 	101
depends 	libgcc-ng >=7.5.0, libgfortran-ng >=7,<8.0a0, libstdcxx-ng >=7.5.0, zlib >=1.2.11,<1.3.0a0
has_prefix 	True
license 	HDF5
license_family 	BSD
machine 	x86_64
operatingsystem 	linux
platform 	linux
subdir 	linux-64
target-triplet 	x86_64-any-linux
timestamp 	1596198389081
```

Is it possible to determine from this information what the right dependency of h5py is? Would it be better/necessary to hardcode the full build as a dependency? Would that make this a https://github.com/conda-forge/h5py-feedstock problem?

**Comment by batterseapower** [comment]
It's interesting that both hdf5 packages you show are v1.10.6, while https://support.hdfgroup.org/ftp/HDF5/releases/ReleaseFiles/hdf5-1.12.0-RELEASE.txt says that S3 support (H5Pset_fapl_ros3) was not added until v1.12.0. I would have thought that neither one of these hdf5 packages would have the appropriate export.

**Comment by hugobuddel** [comment]
Conda seems to agree that package combination that mamba selects, is indeed not conflicting because it is possible to install both manually. This installs, but won't work:
```
conda create -n h5pytest4  "h5py=3.2.1=nompi_py39h98ba4bc_100" "hdf5=1.10.6=nompi_h3c11f04_101"
```

If these packages cannot be used together, then this should be stated somehow in the the dependencies of h5py, otherwise there is no way for the dependency resolver of mamba to know what it should do. So it seems that this is a packaging problem, so perhaps we should report it to https://github.com/conda-forge/h5py-feedstock 

I wouldn't know why an 1.10.6 version works even though it should not have the features. It is not possible to install h5py with hdf5 >= 1.12; neither conda or mamba can resolve that, because all h5py packages require hdf5 <= 1.10. Checking the hdf5 repository suggests that H5Pset_fapl_ros3 [was introduced in 1.11.6](https://github.com/HDFGroup/hdf5/commit/8008294578b5a133907d7ab1dd20e34735c54535) (odd minor numbers are perhaps internal releases?).

**Comment by hugobuddel** [comment]
Apparently S3 support was backported to the 1.10 branch: https://github.com/HDFGroup/hdf5/blob/hdf5-1_10_6/src/H5FDros3.h 

However, then I would expect it to be in each 1.10.6 release.

**Comment by aragilar** [comment]
ROS3 is an optional feature (like MPI). If you're sure you are only using conda-forge as a source (i.e. you haven't added additional sources), then this would be a conda-forge issue (likely the h5py package needs to be rebuilt). *However*, if you do have other sources, then you will need select the correct source for your dependencies (this would be the same as using both Debian stable and Ubuntu LTS on the same system, you're going to get conflicts).

**Comment by hugobuddel** [comment]
Both hdf5 and h5py came from conda-forge. The problem wouldn't be solved by just rebuilding the h5py package because the problem is that the dependencies as specified allow the dependency solver (in this case mamba) to chose combinations of packages that do not work together.

In this case it seems that mamba is more flexible in resolving the dependencies than conda, but that should not really matter because it is possible to break things with conda too. Ideally, any solution that is allowed, should also work. Making dependency management easy is kinda the whole reason-de-être of conda!

MPI is a nice example. This does not work:
```
$ conda create -n h5pytest "h5py=3.2.1=mpi*" "hdf5=1.10.6=nompi*"
...
Package hdf5 conflicts for:
hdf5==1.10.6[build=nompi*]
h5py==3.2.1[build=mpi*] -> hdf5[version='>=1.10.6,<1.10.7.0a0',build='mpi_mpich_*|mpi_openmpi_*']
```

It would be nice if this mechanism can be extended to other build options. (BTW, the inverse, h5py with nompi and hdf5 with mpi, does install, but I guess with mpi is a superset of nompi.)

**Comment by tschaka1904** [comment]
Also just ran into this: 
```  defs.cpython-38-x86_64-linux-gnu.so: undefined symbol: H5Pset_fapl_ros3 ```

Seems like that this as a recent issue for me, as I was able to built it just fine a couple of weeks back. What's the preferred workaround or even solution?

**Comment by ajelenak** [comment]
Difficult to say without more information but it looks like you built h5py using an HDF5 library with enabled ROS3 virtual file driver, and then somehow used that h5py with an HDF5 library that does not have the ROS3 enabled. As far as I know, the plain-vanilla conda forge build of HDF5 does have ROS3 enabled while h5py's wheels available from PyPI do not have ROS3 enabled.

One way to check is to look for ``(Read-Only) S3 VFD:`` line in the _libhdf5.settings_ file. This file should be in the "lib" folder, where the other HDF5 library build files are. I just checked in one of conda environments on my laptop, and this file was in the ``$CONDA_PREFIX/lib`` folder and had ``(Read-Only) S3 VFD: yes`` for ``hdf5-1.12.1-nompi_h2f0ef1a_100``.

**Comment by gregmedlock** [comment]
I am getting the same error at @tschaka1904 without mamba, from conda-forge. Installation from pip avoids the issue.

**Comment by tschaka1904** [comment]
@ajelenak: Is there a way to disable the ROS3 support? I've checked and tested now few versions now, trying to get a way with h5py<3.2, but they all have ROS3 enabled.

**Comment by ajelenak** [comment]
No after the HDF5 library is built. Is it acceptable to pip install h5py, which includes HDF5 library without this driver?

**Comment by tschaka1904** [comment]
Well, pip and conda are not really well known for being good when used together. But.. at this stage I can't see a different option(?)

**Comment by ajelenak** [comment]
Is this issue brought up to conda-forge maintainers of h5py and hdf5? I've never had any problems building h5py with or without ROS3 driver in the HDF5 library. It looks like a mismatch between the hdf5 package used to built the h5py package and the hdf5 package actually being used.

**Comment by carl-drews** [comment]
Thank you @batterseapower for the "downgrade solution". I am using Docker; in my environment.yml file I had to add your solution for h5py before netcdf4 as follows:
  - django-import-export
  **- h5py<3.2**
  - netcdf4
