### ISSUE TITLE
Very opaque error message when opening external links while datasets are open

### ISSUE THREAD

**Issue by rsbyrne** [h5py/h5py#1882]
This subtle behaviour occurs when:
1) Two h5 files have been created.
2) The second h5 file contains an external link to the first h5 file.
3) The second file has been opened in readonly mode (like 'r').
4) A dataset has been created from that file.
5) That same file has been closed...
6) ...and then reopened again in a writeable file mode (like 'r+').

If `del dset` is called after 5) but before 6), there is no error.

It's a surprising behaviour because usually you would expect subsequent file operations to be entirely independent of earlier ones - whereas here, the dataset somehow 'remembers' its preferred file mode and reaches across the program to cause trouble with subsequent file reads. Imagine the havoc if operations 4) and 6) took place in far-apart reaches of the system - what a bastard that would be to debug!

Might I at least suggest a clearer error message for this (admittedly fairly uncommon) usecase?

EDIT:
It occurred to me after posting that the dataset from step 4) should be closed after step 5) - but it looks like it's still open. Does the external link feature somehow 'wedge open' the h5 files?

```python
import h5py
import numpy as np

with h5py.File('file1.h5', mode = 'w') as h5file:
    grp = h5file.require_group('foo')
    grp['bah'] = np.ones(100)

with h5py.File('file2.h5', mode = 'w') as h5file:
    h5file['bah'] = h5py.ExternalLink('file1.h5', '/foo/bah')

with h5py.File('file2.h5', mode = 'r') as h5file:
    dset = h5file['bah']

with h5py.File('file2.h5', mode = 'r+') as h5file:
    dset2 = h5file['bah']

KeyError                                  Traceback (most recent call last)
<ipython-input-7-29e909154a44> in <module>
     10 
     11 with h5py.File('file2.h5', mode = 'r+') as h5file:
---> 12     dset2 = h5file['bah']

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

/usr/local/lib/python3.8/dist-packages/h5py/_hl/group.py in __getitem__(self, name)
    286                 raise ValueError("Invalid HDF5 object reference")
    287         else:
--> 288             oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
    289 
    290         otype = h5i.get_type(oid)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5o.pyx in h5py.h5o.open()

KeyError: "Unable to open object (unable to open external file, external link file name = 'file1.h5')"
```

My specs:

Ubuntu 20.10

Summary of the h5py configuration

h5py    3.1.0
HDF5    1.12.0
Python  3.8.6 (default, Sep 25 2020, 09:36:53) 
[GCC 10.2.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.20.1
cython (built with) 0.29.21
numpy (built against) 1.17.5
HDF5 (built against) 1.12.0

**Comment by takluyver** [comment]
We don't have much control of most error messages (including this one), because they come from the HDF5 C library.

I would guess that `dset` remains open because it belongs to file1. When you access it through file2, HDF5 opens file1, and keeps it open while you've got a reference to an object inside it. Explicitly closing file2 (leaving with `with` block) will close objects that belong to file2, but apparently not objects from another file which were opened through that. `del dset` releases the reference, so HDF5 closes file1 and then is ready to reopen it.

**Comment by takluyver** [comment]
Closing because I don't think there's anything we can practically do about this in h5py; we're pass on error messages from HDF5, and I don't think we should start trying to recognise those and guess a more useful error, especially for corner cases.

Managing access to separate files (for external links, virtual datasets, etc.) is tricky to do transparently - I've [run into](https://forum.hdfgroup.org/t/virtual-datasets-and-open-file-limit/6757/2) other issues around this.
