### ISSUE TITLE
Support for ROS3 in pre-built PyPi package?

### ISSUE THREAD

**Issue by ewildiers** [h5py/h5py#1884]
Hey,

I was wondering if there were any plans to integrate ROS3 driver support in the pre-built PyPi package in the near future? This would be hugely useful as we unfortunately don't have permission to use self-compiled packages

Thanks!
Emmanuel

**Comment by takluyver** [comment]
I'm very reluctant about this because AFAIK, including the ROS3 driver means bundling libcurl and libopenssl (the libraries it uses to communicate with S3), and then we'd have to keep up-to-date with security fixes to those. It's extra weight and extra risk for a feature that most users don't need. Also, I think that HDF Group see the VOL - Virtual Object Layer - as the way forwards for supporting things like cloud object storage, not the ROS3 virtual file driver.

Of course, anyone can build h5py packages with ROS3 support enabled and upload them to PyPI under another name. You can even set up a CI service like Github actions to automate this. But I don't think we should do it for the default h5py wheels.

Alternatively, I think conda-forge builds conda packages with ROS3 enabled by default, if you're happy using conda.

**Comment by ewildiers** [comment]
@takluyver thanks for clarifying Thomas! 

I may be totally wrong here, but I think the main difference between ros3 and the alternative with something like an s3fs file object is that ros3 is much more efficient at reading specific small datasets out of a large HDF5 file. When doing side by side comparisons, I'm getting speedups of 40x when reading a single small dataset from a 1GB HDF5 file stored on S3.

Conda is unfortunately not an option for us, but we can indeed investigate the alternative PyPi package route. I would just expect that, given the importance of S3, many h5py users would benefit from the benefits that the ros3 driver has to offer?

**Comment by takluyver** [comment]
I'm sure there are plenty of people who would benefit from S3 support, but there are also a lot of people who don't need it, and pushing bundled networking libraries onto all those people seems like a really bad idea.

And given the new virtual object layer in HDF5 1.12, I think that will be the preferred direction for HDF5 data in cloud storage. This is entirely separate from h5py's support for passing in Python *file-like objects* (like s3fs objects). VOL is quite new and unfortunately I don't think there are great docs about it yet, but you can see the guide HDF group produced here: https://bitbucket.hdfgroup.org/projects/HDFFV/repos/hdf5doc/browse/RFCs/HDF5/VOL/user_guide/vol_user_guide.pdf

**Comment by ewildiers** [comment]
@takluyver thanks Thomas, I understand your point. Will have a look at VOL and perhaps I can help integrating it into h5py in the future!

**Comment by antoinetran** [comment]
Hi @ewildiers , do you have news related to VOL for S3 native support in hdf5? Indeed we uses hdf5-ros3 and needs to build and maintain our own hdf5 version, which is not ideal.
