### ISSUE TITLE
Due to the upgrade tensorflow2.5.0,I cannot load weights which tf2.4.0 canload,maybe the reson is the h5py from 2.10.0 to 3.1.0,I want to use tf2.5.0 to load the pretrain model,how can I do?

### ISSUE THREAD

**Issue by successAI** [h5py/h5py#1895]
To assist reproducing bugs, please include the following:
 * Operating System (e.gWindows 10)
 * Python version (e.g. 3.7.10)
 * Where Python was acquired ( Anaconda on
   Windows)
 * h5py version (3.1.0)
 ValueError: in user code:

    E:\git_projects\segmentation\deeplabv31\subpixel.py:91 call  *
        return self._phase_shift(super(Subpixel, self).call(inputs))
    D:\software\soft\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\layers\convolutional.py:273 call  **
        outputs.set_shape(out_shape)
    D:\software\soft\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\framework\ops.py:777 set_shape
        raise ValueError(str(e))

    ValueError: Dimension 1 in both shapes must be equal, but are 150 and 1200. Shapes are [?,150,150,128] and [?,1200,1200,2].

**Comment by tacaswell** [comment]
There is no h5py in this traceback so I do not think that this is related to changing the h5py / hdf5 version.

I suggest you report this issue to either keras or tensorflow. They will greatly appreciate if you include a runable example or a script that will train a model with TF2.4 that fails to load with TF2.5.

I'm closing this because there is nothing actionable on the h5py side.
