### ISSUE TITLE
libhdf5 bug fix deployment?

### ISSUE THREAD

**Issue by woutdenolf** [h5py/h5py#1942]
I'm wondering what the strategy is of releasing `h5py` on pypi and conda. Currently we have one `libhdf5` deployed per `h5py` version (both pypi and conda) which does not allow including bug fixes in `libhdf5`. For example `h5py 2.10` ships with `libhdf5 1.10.4` while currently we are at `libhdf5 1.10.7`. Would it be feasible to deploy additional packages for each h5py version with upgraded `libhdf5`? Or perhaps create a new h5py release every time `libhdf5` 1.10.x or 1.12.x is released?

Who is managing the conda packages? And what is the "official" channel? We have h5py on the default channel and on conda-forge https://anaconda.org/search?q=h5py

**Comment by takluyver** [comment]
For PyPI: I'd like to consider the pre-built wheels as a convenience thing, for people who are happy enough with getting some recent HDF5 version from the time the h5py release was made. If you need it with a newer or older version of HDF5, it should be reasonably practical to build h5py from source, or use something like conda or Spack that's capable of tracking non-Python packages explicitly.

I wouldn't say there is an 'official' conda channel. conda-forge is probably a bit quicker with new versions, but some people will prefer to get all their packages from Anaconda inc. rather than trusting even more random people on the internet. I haven't got involved in the conda-forge packaging; you can [see here](https://github.com/conda-forge/h5py-feedstock/graphs/contributors) who has contributed to it.

**Comment by tacaswell** [comment]
I agree with @takluyver, the canonical version of h5py is the sdist, if you have specific libhdf5 needs 

```
pip install h5py --no-binary h5py
```

(see https://docs.h5py.org/en/stable/build.html#custom-installation for the ENVs that control how we find libhdf5 as well)

Anacanda-the-company is responsible for the "default" conda channel, there is a community of people (and an army of bots!) who manage the "conda-forge" channel.  From the point of view of h5py, those are on the same footing as the debian / fedora / suse / ... packaging efforts (where they are also packaging libhdf5 and are responsible for making sure the h5py binaries and the libhdf5 binaries are compatible.

Until very recently, for very good reasons, there was no way to upload a new wheel with the same name as a name you had previously uploaded which means that if we want to rebuild the wheels with a different libhdf5 we would have to do a new micro-release.  I think there is now a way to gracefully replace wheels with rebuilt versions without doing a new release, but I could not find the documentation on that.

We also discussed this issue at https://github.com/h5py/h5py/issues/1909#issuecomment-865127429 .  That said, if there is a critical bug in a version of libhdf5 (like drastically wrong results, segfault, or security) with a version of libhdf5 we should consider doing a release, but like @takluyver I am hesitant to guarantee that we will also do such rebuilds.

**Comment by takluyver** [comment]
I should add that I'm trying to aim for a quicker release schedule in general, so if your concern is just getting the latest HDF5 in a wheel, that should go some way to address it. I'm not aiming to do an h5py release whenever an HDF5 release happens, but maybe every 2-3 months rather than once a year.

**Comment by ajelenak** [comment]
Interesting discussion... I have a related question: Who builds the libhdf5 that is used in h5py wheels and can those builds enable the "ros3" (read-only S3 VFD) driver? I tried the pip-installed h5py 3.3.0 and it did not seem to support this driver.

**Comment by takluyver** [comment]
We build it as part of our CI. I am reluctant to build a network access feature by default that I suspect many users do not need - see #1884 for more discussion of that.

This kind of thing is a big part of why I want to consider the wheels just a convenience. Python packaging doesn't really handle compile time options, so we more or less have to pick some set of options which inevitably aren't right for everyone (unless we go to a whole load of extra effort, e.g. releasing h5py-ros3, h5py-mpi, h5py-mpi-ros3 as separate packages).

**Comment by aragilar** [comment]
@ajelenak See #1884 (as @takluyver mentioned), that increases the complexity of providing secure wheels (we don't want to be chasing every CVE in libcurl or openssl).

I agree with both Toms that if someone wants something custom, setting up their system to manage their whole dependency tree (whether that's using a package manager or simply being able to build from source) is going to be a better time investment for them (so they're not tied to h5py's timelines, or anyone else's).

As for releasing multiple wheels, I think psycopg did that, and moved away from it due to too many issues (I'm not sure of the details though).

**Comment by woutdenolf** [comment]
@takluyver @tacaswell Point well made, thanks.

Then would it be possible to have a place for the libhdf5 build parameters that were selected to build the pypi wheels?

For me it is not straightforward to understand all the build options. I'm guessing it's more or less this:

```
git clone https://github.com/HDFGroup/hdf5.git
cd hdf5
git checkout -t upstream/hdf5_1_10
git checkout tags/hdf5-1_10_7

local prefix=$(pwd ./build_1_10_7)
rm -rf ${prefix}

rm -rf build
mkdir -p build
cd build

cmake -DBUILD_SHARED_LIB:BOOL=ON \
          -DDEFAULT_API_VERSION:STRING=v18 \
          -DHDF5_USE_FILE_LOCKING:BOOL=ON \
          -DHDF5_IGNORE_DISABLED_FILE_LOCKS:BOOL=ON \
          -DHDF5_ENABLE_ALL_WARNINGS:BOOL=ON \
          -DHDF5_ENABLE_PARALLEL:BOOL=OFF \
          -DCMAKE_INSTALL_PREFIX:PATH=${prefix} \
          -DBUILD_TESTING:BOOL=OFF \
          -DHDF5_BUILD_EXAMPLES:BOOL=OFF \
          -DHDF5_ENABLE_Z_LIB_SUPPORT:BOOL=ON \
          -DHDF5_ALLOW_EXTERNAL_SUPPORT:STRING=NO \
          ..

cmake --build . --target install --config Release
```

**Comment by takluyver** [comment]
The scripts which build HDF5 are [get_hdf5_if_needed.sh](https://github.com/h5py/h5py/blob/master/ci/get_hdf5_if_needed.sh) for Mac, and [get_hdf5_win.py](https://github.com/h5py/h5py/blob/master/ci/get_hdf5_win.py) for Windows. For Linux, the HDF5 used to build wheels is actually built into a Docker image from a separate repository: [install_hdf5.sh](https://github.com/h5py/hdf5-manylinux/blob/master/install_hdf5.sh).

I don't think there's a great way to see this at runtime. You can get the HDF5 version it was built with (`h5py.version.hdf5_built_version_tuple`), and whether h5py itself (not HDF5) was built with MPI & ROS3 support (`h5py.get_config().mpi` and `.ros3`).

**Comment by woutdenolf** [comment]
@takluyver Thanks!

Btw does anyone understand the logic of the branches on https://github.com/HDFGroup/hdf5? For example we have `1.10/master`, `hdf5_1_10`, `hdf5_1_10_7`, `master`, `develop`...

**Comment by takluyver** [comment]
Not me :wink:

**Comment by tacaswell** [comment]
I would also add that if @ajelenak or someone else from the hdf5 group wants to take over building and publishing the wheels I will not stand in the way of any level of complexity :)

My views here are based on what we can reasonably do with the volunteer/community effort we have now.

**Comment by woutdenolf** [comment]
> Btw does anyone understand the logic of the branches on https://github.com/HDFGroup/hdf5? For example we have `1.10/master`, `hdf5_1_10`, `hdf5_1_10_7`, `master`, `develop`...

https://github.com/HDFGroup/hdf5/blob/develop/doc/branches-explained.md

**Comment by ajelenak** [comment]
> @ajelenak See #1884 (as @takluyver mentioned), that increases the complexity of providing secure wheels (we don't want to be chasing every CVE in libcurl or openssl).

Makes sense. Better to have a package management system other than `pip` deal with increased number of dependencies.

I note that conda-forge moved last week to HDF5-1.12.1 with the `ros3` driver enabled.

**Comment by takluyver** [comment]
Yup, conda-forge has opted to enable ROS3 by default, so that's probably the easiest path for people who want to use it but don't want to build HDF5 themselves. I guess it's easier there because libcurl and openssl are separate packages, so the HDF5 & h5py maintainers shouldn't have to do anything for new bugfix versions of those.
