### ISSUE TITLE
Memory Leak with Slice operator

### ISSUE THREAD

**Issue by DocDriven** [h5py/h5py#2013]
To assist reproducing bugs, please include the following:
 * Operating System (e.g. Windows 10, MacOS 10.11, Ubuntu 16.04.2 LTS, CentOS 7) Ubuntu 18.04
 * Python version (e.g. 2.7, 3.5) 3.8
 * Where Python was acquired (e.g. system Python on MacOS or Linux, Anaconda on
   Windows) Docker image
 * h5py version (e.g. 2.6) 3.5.0
 * HDF5 version (e.g. 1.8.17) 1.12.1
 * The full traceback/stack trace shown (if it appears)

h5py    3.5.0
HDF5    1.12.1
Python  3.8.10 (default, Sep 28 2021, 16:10:42) 
[GCC 9.3.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.21.3
cython (built with) 0.29.24
numpy (built against) 1.17.5
HDF5 (built against) 1.12.1

I am experiencing a bug similar to this issue (https://github.com/h5py/h5py/issues/1176), the difference being that the kernel kills the program, not myself. Message displayed is simply ``Killed``. The bug appears when the amount of data in the slice exceeds the available RAM, in my case 5000 instances seem to be drawn into RAM before iterating it.

Code to reproduce this issue:

```
import h5py
h5file = 'testfile.h5'
dset_name = 'test_dset'

a = 0
with h5py.File(h5file, 'r', swmr=True) as f:
    for sample in f[dset_name][:5000]:
        a += 1
```

The bug disappears when removing the slice operator OR as a workaround when using itertools.islice on the dataset. I decided to open the issue because the referenced topic is almost three years old. 

Can you confirm whether or not this bug is a problem of h5py or the underlying library? In the latter case, I would then report the bug directly to the HDFGroup and post any updates here.

Best regards,
Sebastian

**Comment by tacaswell** [comment]
`f[dset_name][:5000]` is asking h5py to pull up all of the data in the selection into a single numpy array, which if it is bigger than your RAM will (correctly) fail.

If you directly iterate on the `DataSet` object that is the same as

```python
ds = f[dset_name]
for j in range(N):
    a += f[j]
```

which will only pull up 1 first-dimension slab at a time.  This will be more memory efficient (because it only pulls up 1 chunk at a time), but will be slower (because you are making N calls to libhdf5 with the associated book-keeping and I/O).

I am not sure exactly what `islice` is doing under the hood, but I am relatively sure that it is wrapping the iterator and hence will have the same performance trade offs.

From your description I do not think I would call this a "leak" per-say.  In a typical leak case there is some loop that each time through allocates some (small amount) of RAM and then even though it _should_ have been released it is not (e.g. in a c/c++ case you drop all the pointers(!) in a Python case maybe have some data structure keeping objects alive too long).  Over time this "leak" will monotonically increase and eventually eat all of your RAM until it is killed.

If you want the best performance, you may want to write a second loop where you pull stuff up by chunk:

```python
ds = f[data_set]
for s in ds.iter_chunk():
    for plane in ds[s]:
        a += plane
```

which will get you a sequence of slices to get the numpy arrays of each chunk.  This should hopefully both keep you under the memory limits of your machine (assuming that both the chunks and your machine are reasonably sized) and give you the best performance I/O wise as you only pull each chunk up once.  You can pass a selection to `iter_chunks` if you do not want to do the whole dataset.

**Comment by takluyver** [comment]
@tacaswell already gave much more detail, but just to confirm, slicing like `dset[:5000]` is how you tell h5py to read a section of your data into memory. So if you read a slice bigger than the available memory, running out of memory and getting your process killed is exactly what you should expect to happen.
