### ISSUE TITLE
Setting data alignment at File creation

### ISSUE THREAD

**Issue by hmaarrfk** [h5py/h5py#2034]
I'm hoping to add data alignment strategies to certain files. This can be achieved by adding parameters to `make_fapl` in:

https://github.com/h5py/h5py/blob/master/h5py/_hl/files.py#L111

Using `set_alignment`. We would need to add 2 parameters, the threshold, and the alignment interval.

One would need to add the lines
```
def make_fapl(...., threshold=1, alignment_interval=1):
    fapl.set_alignment(threshold, alignment_interval)
```
and provide additional parameters to the `File` constructor.

Would this be an acceptable PR to make?

Thank you!

References: https://support.hdfgroup.org/HDF5/doc/UG/FmSource/08_TheFile_favicon_test.html

To assist reproducing bugs, please include the following:
 * Operating System (e.g. Windows 10, MacOS 10.11, Ubuntu 16.04.2 LTS, CentOS 7): Linux
 * Python version (e.g. 2.7, 3.5): 3.9
 * Where Python was acquired (e.g. system Python on MacOS or Linux, Anaconda on
   Windows): conda-forge Linux
 * h5py version (e.g. 2.6): 3.6.0
 * HDF5 version (e.g. 1.8.17): 1.12.1

**Comment by takluyver** [comment]
That seems reasonable enough to me - we've already gone for lots of keyword parameters for `File()`. @tacaswell, are you OK with adding a couple more?

I'd probably call them `alignment_threshold` (to make it clear what threshold it is) and `alignment` (following the name HDF5 uses).

**Comment by hmaarrfk** [comment]
There might be some other configuration that would be desirable for performance reasons, cache size, and whatnot.

Do you wan tto make the fapl and fack overwrite able instead? not very high level, but gives the most control

**Comment by tacaswell** [comment]
So long as they are un-coupled (that is the user can correctly set just a sub-set) I'm :+1: on adding as many extra keyword-only arguements to `File` as we need to expose everything in facl.

If there are a bunch of the inputs that _only_ make sense when the file is created (rather than just opened), what do people think of adding some `classmethod` constructors instead of adding to the `__init__` methods?  It might require a bit of jiggery-pokery, but I think we could make it work without having to close and then re-open the file...

**Comment by hmaarrfk** [comment]
@tacaswell great.

This is an access parameter, so I believe it is valid both at creation time and at open time.
