### ISSUE TITLE
add fields to a structured array

### ISSUE THREAD

**Issue by blueForestIcarus** [h5py/h5py#2048]
It is possible in h5py to add both rows and columns to an array, but if you use a structured array instead of columns, there doesn't seem to be any way to add fields. 

In my particular application this has meant I can't store the data as a structured array, and have to convert to and from, handling the field widths. This seems like something h5py could handle itself.

**Comment by aragilar** [comment]
@blueForestIcarus Do you mean add fields to an existing dataset? I'm not sure HDF5 allows that (but I could be wrong). Do you have an example of what you're trying to do?

**Comment by takluyver** [comment]
If you use a compound dtype, with multiple fields in one array, I'm pretty sure that's a limitation of HDF5. The 'rows' are stored one after another - if you have fields a, b, c, then the data will be stored like `abcabcabc`. So there's no room to add a field d without rewriting the whole dataset.

If your columns all have the same dtype, then as you mentioned, you can use a 2D array and track the column names separately (e.g. in an attribute). This works because HDF5 chops your array up into chunks of a fixed shape. E.g. if you make chunks of 5 columns by 100 rows, adding the 6th column will allocate new chunks in the file, but the 7th-10th columns will fill in space in those chunks.

You can also store each column in a separate dataset, so column names become dataset names within a group. This is probably better if your columns have different dtypes. But if you're adding rows, it's up to your code to ensure the different datasets don't get out of sync - which is probably dead easy 99% of the time, and quite fiddly the other 1%.

If neither of those options work, HDF5 might not be what you want.

**Comment by blueForestIcarus** [comment]
I am confused on why adding columns is different from adding fields? 
If you have a chunked file, why can't new fields be allocated to new chunks, the same as new columns?

A structured array is just a regular 2d array together with the offset+type metadata, right?

**Comment by ajelenak** [comment]
Adding new fields to an existing compound (struct) datatype is not possible. The datatype of an HDF5 dataset is a fundamental property set at that dataset's creation and immutable thereafter.

**Comment by blueForestIcarus** [comment]
Is there any difference in how the data is stored.
between a 4 column array of floats, and a structured array of 4 floats

**Comment by takluyver** [comment]
You're right in principle - you could build a format which allowed for adding new named fields in the same way as extending a dimension. But that's not how HDF5 approaches it. The fields in HDF5 are part of the datatype, which is set when you create a dataset, and not something you can extend later.

You can always create a new named dataset with another simple 1D array, though.

**Comment by ajelenak** [comment]
Yes. The first is rows by 4 (2D) dataset of floats, the second is rows (1D) dataset of a 4-float compound datatype.

If you want to add new fields, a.k.a. columns, then the suggestion to turn each compound field into a separate 1D HDF5 dataset is the only approach.

**Comment by ajelenak** [comment]
@blueForestIcarus Note that what matters is not only how bytes are stored, but how they are interpreted. And that interpretation is only according to the dataset's datatype. So, if a float datatype means that every four or eight bytes will interpreted as one dataset element. For a compound datatype of four floats, 16 or 32  bytes will be interpreted as one dataset element.

**Comment by blueForestIcarus** [comment]
Is there a performance impact?

What I have done, is to make a 2d array of 4byte ints, and use that to store the raw data of the structured array.
If I need to add fields, I just add columns. 
I made it 4bytes because I didn't want to worry about alignment.
I didn't make it multiple datasets because I didn't want to worry about rows getting out of sync.

I store the column names as metadata and am able to build the structured array dtype from that, and get a useable object using .view()

**Comment by takluyver** [comment]
> Is there a performance impact?

No idea - if it matters, time it. :slightly_smiling_face: 

Personally, I'd only do what you describe if all the columns are 4-byte integers and you just want to attach names to them. If you're storing other types, then all the normal tools for viewing HDF5 files will show you garbage, because they're trying to present it as int32. But that's up to you.

> Could this be done a different way. With Virtual Datasets maybe?

I don't think so. Virtual datasets give you a stitched-together 'view' of several underlying datasets, but for different parts of the dataspace, not different fields within the data type.

**Comment by takluyver** [comment]
I'm going to close this issue, because it's a limitation of HDF5, so there's nothing for h5py to do. You could ask HDF group to consider it as a new feature - help@hdfgroup.org or https://forum.hdfgroup.org/ - but I imagine it would be a pretty big change, so I wouldn't hold my breath.

To recap, a few workarounds were suggested, all of which have some drawback:

- 1 dataset per column (drawback: need to ensure adding rows stays lined up across datasets)
- Extra resizable dimension, viewed as columns (drawback: if your columns have different types, the data will be garbage when reading the HDF5 file normally, because you have e.g. float data in an integer dtype)
- Don't use HDF5 at all (drawbacks depend on what you use instead)
