### ISSUE TITLE
use dataset and group in context manager

### ISSUE THREAD

**Issue by d-v-b** [h5py/h5py#2061]
it would be convenient for groups and datasets to support usage within a context manager, e.g.:

```python
with h5py.File('foo.h5', mode='w').create_dataset(name='s0', shape=(10,10)) as ds:
    # do stuff with dataset
    ds[0,0] = 1

# the file is now closed
```
Is there any blocker for this, or should I put together a PR?

**Comment by tacaswell** [comment]
A context manager suggests to me that there is some start up / shut down logic that needs to be done.  With `Files` this makes sense because we are grabbing / releasing an external resource (file handle).  However with groups or datasets there is no creation (well in this example there is but `g['foo']` would also work in general) or cleanup that should be done.

This although I see why in _this_ case it is nice (saves you from having 1 free variable and a line of code), I think in the bigger picture having groups / datasets act as (no-op) context managers will be more confusing because it will (incorrectly) imply that some cleanup done which will confuse users.  

I am 👎🏻 on this, but won't block it if @takluyver and @aragilar are for it.

**Comment by takluyver** [comment]
Dataset/group being a context manager which closes the file makes no sense to me.

You can already do the original example with the same number of lines and variables:

```python
with h5py.File('foo.h5', mode='w') as f:
    f.create_dataset(name='s0', shape=(10,10))[0, 0] = 1
```

But clarity is usually better than brevity:

```python
with h5py.File('foo.h5', mode='w') as f:
    ds = f.create_dataset(name='s0', shape=(10,10))
    ds[0, 0] = 1
```

I could see a case for datasets being a context manager which closes the specific dataset on exit. If you're writing to a dataset, HDF5 may buffer the writes and not actually perform all of them until the dataset is closed. So explicitly closing a dataset object can make sense as a way to commit any cached writes - and raise errors if there are any, rather than hiding them in a `__del__` / `__dealloc__` method where you can't really handle them.

**Comment by mkitti** [comment]
There are dataset handles that can be closed by H5Dclose:

https://portal.hdfgroup.org/display/HDF5/H5D_CLOSE

The dataset context should be nested within the file or group contexts.

This is made easier with Python 3.10 parenthesized context managers:
https://docs.python.org/3/whatsnew/3.10.html#parenthesized-context-managers

Ideally all `hid_t` allocated objects should have a context manager so that the user can explicitly close out spaces, property lists, groups, and datasets. Currently h5py relies on the file context to close out everything which sometimes does not succeed due to references leaking out and may lead to concurrency issues.

**Comment by aragilar** [comment]
`contextlib.closing` can be used to create context managers which close as needed (given anything that subclasses from `ObjectID` has a close method). I'm definitely not a fan of the implicit closing given above, but if someone wanted to add the equivalent of `contextlib.closing` to classes where it would work, I'd be fine with that.

**Comment by mkitti** [comment]
I would revise @d-v-b 's original request to enable the following nested context managers like this:

```python
with h5py.File('foo.h5', mode='w') as f
    with f.create_dataset(name='s0', shape=(10,10)) as ds:
        # do stuff with dataset
        ds[0,0] = 1
    with f.create_dataset(name='s1', shape=(10,10)) as ds:
        # do stuff with dataset
        ds[0,0] = 1
```

With Python 3.10 and for a single dataset:
```python
with (
    h5py.File('foo.h5', mode='w') as f,
    f.create_dataset(name='s0', shape=(10,10)) as ds
):
    # do stuff with dataset
    ds[0,0] = 1

**Comment by mkitti** [comment]
`H5Dclose` is exposed at the API level here:
https://github.com/h5py/h5py/blob/571b926b2143269a012799027998cdf177b7babc/h5py/api_functions.txt#L86

However, it is currently not available in the low-level API.

**Comment by d-v-b** [comment]
My actual use case is a function that takes in a filename and returns either a group or a dataset, e.g.:

```python
def access(container, component):
    return h5py.File(container, mode=r)[component]

group_or_dataset = access('foo.h5', 'bar')
```

I'd like to make it simple for consumers of this function to cleanly close the underlying file when they are done with the `Group` or `Dataset`. This is simple if `Group` and `Dataset` both have `__exit__` methods that call `self.file.close()`, even if the semantics of "closing a dataset" might be mushy. But I'm open to other solutions to this problem. I wonder if this function is considered an anti-pattern for hdf5?

**Comment by mkitti** [comment]
I would not expect closing a dataset to close the entire hierarchy above it by default since there may be additional peer datasets. Perhaps this might make sense as a non-default option.

What seems to be missing from your interface is the ability to open and close a container.

```python
def get_hdf5_container(path):
   h5py.File(path, mode='r')


with get_hdf5_container(path) as container:
   with access(container, component) as group_or_dataset:
        # do stuff with group_or_dataset
```

Otherwise, perhaps a high level abstraction such as hyperspy may make sense:
https://hyperspy.readthedocs.io/en/stable/user_guide/big_data.html#loading-lazily

**Comment by mkitti** [comment]
This seems related:
https://github.com/dask/dask/issues/922

**Comment by tacaswell** [comment]
Fair, regarding `H5Dclose`.  We wrap that function, but do not seem to actually use it.  However, my read of that documentation and looking at the source this function just decrements the reference count on the c-struct and relies on {hdf5's) garbage collection to actually release the resources https://github.com/HDFGroup/hdf5/blob/ba032bb28bfff3b8d330b026cbd01e6e44be7578/src/H5D.c#L448-L479

We similarly have a `close` method on the low-level proxy objects, (Python-side proxies for the underlying c-structs), however in all cases but `File`, they decrement the hdf5-side reference count and decouple themselves from that struct: https://github.com/h5py/h5py/blob/96b5c682b54b8376cf19ba8e7bbebfc450cdd3eb/h5py/_objects.pyx#L211-L224
We also do this in the `__dealloc__` cython method (along with some other house keeping).

I think given the discussion between @mkitti and @d-v-b (which given you are both at Janelia I infer you work together) I am going to assert that what users would "expect" for closing a dateset is very unclear!

I disagree that the dask issue is related.  I think this is primarily related to the fact that the computation graph holds references to h5py objects (which in turn hold references to c-structs and file handles) which do not serialize well! 

From the description I think you can get away with a function like

```python
import contextlib
import h5py


@contextlib.contextmanager
def file_like_context(fname, shape, *, dset_name="bob", mode="a", dtype=float, **kwargs):
    F = h5py.File(fname, mode=mode)
    try:
        # or what ever other access you want to do
        yield F.require_dataset(dset_name, shape, dtype, **kwargs)
    finally:
        F.close()


with file_like_context('/tmp/test.h5', (10, 10)) as ds:
    ...

```

which will make sure the underlying file is closed on exiting the context, only exposes the dataset/group to your user, and does not introduce any new semantics up stream.

**Comment by d-v-b** [comment]
@tacaswell that example is great, thanks! I think it will suit my needs exactly, and I'm happy to close this once the conversation is over.

As an aside, what prevents h5py from being lazier and only holding a file handle when doing IO, and releasing immediately after? Presumably this has been proposed or discussed before, so feel free to point me to that content.

**Comment by tacaswell** [comment]
Opening / closing hdf5 files can be pretty expensive (hdf5 is a complex file format and on open libhdf5 builds a whole bunch of state).  Similarly, accessing groups / datasets is not-free, being able to hold on to a reference to the h5py object can give you big speed ups.  One very easy way make code faster is to pull opening hdf5 files / accessing groups / accessing data sets out of loops.  

At the data set level, libhdf5 manages a cache for chunks, on both reading / writing.  If you are going back to the same dataset multiple times (and your access patterns sync with the chunks and you have enough RAM) you can avoid a bunch of disk I/O.

The analogy of `h5py.File` as "nested dict of numpy arrays" is conceptually very powerful, but the abstractions leak pretty quickly.
