### ISSUE TITLE
Why H5PY is still an issue with tensorflow installation for ARM devices 🤷‍♂️?

### ISSUE THREAD

**Issue by UcefMountacer** [h5py/h5py#2073]
To assist reproducing bugs, please include the following:
 * Operating System Ubuntu 20.04 64bits
 * Python version 3.8
 * Where Python was acquired on Linux (with pip)
 * h5py version 3.1
 * HDF5 version no idea

**Comment by aragilar** [comment]
@UcefMountacer This needs more details:
* What specifically is the issue (I'm guessing it's related to installing tensorflow, but have you installed h5py already)?
* There are many ARM devices, which one is this?
* Why are you installing h5py 3.1, 3.6 is the latest release, which does include an aarch64 wheel?

**Comment by UcefMountacer** [comment]
Hello @aragilar

Thanks for the quick response. My problem is related to tensorflow indeed, on the raspberry pi with Ubuntu 20.04 64bit.

I'm using a tensorflow wheel (probably generated by community). This wheel requires h5py 3.1, which can't be installed on this device. I remember having this same issue on the jetson Nano.

The working version is h5py 3.6, but tensorflow requires 3.1. Even when installed, tensorflow still requires 3.1.

Thanks, I guess this is related more to tensorflow....

**Comment by tacaswell** [comment]
If you want to use pip for package management you are going to have to install from source on your arm device.  Please see https://docs.h5py.org/en/stable/build.html#source-installation and make sure you have the external dependencies (libhdf5 + compiler) on your system.  

It looks like conda-forge has builds for aarch64 back to h5py3.1: https://anaconda.org/conda-forge/h5py/files?sort=ndownloads&version=3.1.0&sort_order=desc .   You may also want to look at install h5py through yous system package manager (assuming that is where you get Python from).

It is very unlikely that we are going to go back and build arm wheels for old versions of h5py.

I'm going to close this because based on the information here, there in nothing we could change upstream to fix this.  If there are issues with the installation (once all of the dependencies are installed) that persist in the currently release version please ping to have this re-opened.
