### ISSUE TITLE
h5py hangs with 100% cpu load while reading attribute.

### ISSUE THREAD

**Issue by sergey-komissarov** [h5py/h5py#2088]
Hello,

I'm trying to read attached HDF file and see that python hangs forever. Is it possible to check such files before opening or raise an exception instead of inifinite loop? I know that corrupted files are hard to deal with but hanging application is also pretty bad from the user view. 

File causing the problem: [r.zip](https://github.com/h5py/h5py/files/8591339/r.zip)

Code to reproduce:
```python
import h5py
with h5py.File("r.h5") as f:
  gr = f[list(f.keys())[0]] # get first group
  print(list(gr.attrs)) # ['@properties', '@type']
  gr.attrs[list(gr.attrs)[0]] # read first attribute
```

My system:
h5py    3.6.0
HDF5    1.12.1
Python  3.8.10
Ubuntu 20.04

**Comment by herclogon** [comment]
It doesn't just hang, it starts to load the CPU at 100%.

**Comment by tacaswell** [comment]
I can reproduce this via

```
h5dump -r r.h5
```

so this needs to be reported upstream to the hdf5group.  I am going to close this because in general we do not work around bugs in libhdf5 at the Python layer.  If you have a specific patch you would like to propose to detect and avoid this I think we would consider it depending on the complexity.

It will be helpful to hdf5 group if you could provide code to generate that file.

----

Having 3 people definitely from the same company (and I assume the 4th is as well) all react does not actually convey that this is a widespread problem that needs prompt attention.

**Comment by takluyver** [comment]
Just to record, a follow up issue was opened on HDF5 here: https://github.com/HDFGroup/hdf5/issues/1707
