### ISSUE TITLE
Info for SWMR - Append mode

### ISSUE THREAD

**Issue by scarsi99** [h5py/h5py#2145]
Dear all,

I am currently producing data from CERN beam tests and saving in HDF5 format using this library

Reading the docs, I've found the SWMR mode, which would be very useful for  my applications

I have understood how to create a file and set this mode as well as how to read a file specifying to read in SWMR mode

My question is: if i want to open a file in append mode, what should I do? Should i pass SWMR=True as I do opening in read mode)? Or should i set the parameter as I do when I open in write mode for the first time? Or nothing has to be done

Kind Regards

Stefano Carsi

**Comment by takluyver** [comment]
It should be the same as when you open it in write mode - you want to be the single writer (SW) part of SWMR, regardless of whether the file is newly created or already exists.

The reason this is done in a separate step is so that you can set up the file structure (creating groups and datasets) before starting SWMR write mode.

**Comment by takluyver** [comment]
Yes, I think that's right.
