### ISSUE TITLE
[Feature request] on-disk nbytes of dataset

### ISSUE THREAD

**Issue by bendichter** [h5py/h5py#2177]
When I look at a dataset in HDFView, I can see the compression ratio of each dataset. Is there a way to access this data in h5py? `Dataset.nbytes` returns the uncompressed size, but I don't see a way to access the on-disk size.

**Comment by takluyver** [comment]
The low-level API has it - call `dset.id.get_storage_size()` ([docs](https://api.h5py.org/h5d.html#h5py.h5d.DatasetID.get_storage_size)).

However, there are some caveats, because if not all of the dataset has been written, there may be chunks which don't exist in the file at all (you could argue this is a kind of compression). You might want to check:

- The layout - `dset.id.get_create_plist().get_layout()` ([docs](https://api.h5py.org/h5p.html#h5py.h5p.PropDCID.get_layout)). Only chunked datasets can use compression.
- How many chunks are allocated - I think `dset.id.get_num_chunks()` ([docs](https://api.h5py.org/h5d.html#h5py.h5d.DatasetID.get_num_chunks)) will give you this.
- Whether there's any margin at the edges of your dataset - e.g. if your dataset size is 70 and the chunk size is 50, you're allocating space for 100 elements, even if 30 are never filled. If your data size is much larger than your chunk size, though, this difference will be small.

**Comment by bendichter** [comment]
This is exactly what I was looking for. My only criticism would be that this is a bit hard to find in the docs. It would be great to have a pointer to this method [here](https://docs.h5py.org/en/stable/high/dataset.html#h5py.Dataset.nbytes).

**Comment by ajelenak** [comment]
I created [this](https://gist.github.com/ajelenak/997c9ab4879a3a66fb5720e90d36c79e#file-h5comprat-py-L5-L11) short gist as an answer to a similar question on the HDF Forum last year. Perhaps that code should be turned into something like `Dataset.comprat` property?
