### ISSUE TITLE
Openning hdf5 file over https using fsspec

### ISSUE THREAD

**Issue by John-Ragland** [h5py/h5py#2185]
I'm trying to open a hdf5 file over https without having to download the file to disk. I'm not sure if this is the right way to go about this, but this is what I currently have. (The file is publicly available and should work for anyone else as well, It's about 1.2 GB if you download it)

```
import fsspec
import h5py

url = 'http://piweb.ooirsn.uw.edu/das/data/Optasense/SouthCable/TransmitFiber/South-C1-LR-95km-P1kHz-GL50m-SP2m-FS200Hz_2021-11-01T16_09_15-0700/South-C1-LR-95km-P1kHz-GL50m-SP2m-FS200Hz_2021-11-01T231514Z.h5'

of = fsspec.open(url)

with of as f:
    hf = h5py.File(f)
    print(hf['Acquisition']['Raw[0]'].keys())
    
    print(hf['Acquisition']['Raw[0]']['RawData'])
```
I'm able to successfully read the keys from the opened file, but when I attempt to view the Dataset, I get the following error:

Expected result:
```
<KeysViewHDF5 ['Custom', 'RawData', 'RawDataTime']>
<HDF5 dataset "RawData": shape (47500, 12000), type "<i4">
```
Actual Result:
```
<KeysViewHDF5 ['Custom', 'RawData', 'RawDataTime']>
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [29], in <cell line: 8>()
      9 hf = h5py.File(f)
     10 print(hf['Acquisition']['Raw[0]'].keys())
---> 12 print(hf['Acquisition']['Raw[0]']['RawData'])

File h5py/_objects.pyx:54, in h5py._objects.with_phil.wrapper()

File h5py/_objects.pyx:55, in h5py._objects.with_phil.wrapper()

File ~/anaconda3/envs/ooi_dev/lib/python3.10/site-packages/h5py/_hl/group.py:328, in Group.__getitem__(self, name)
    326         raise ValueError("Invalid HDF5 object reference")
    327 elif isinstance(name, (bytes, str)):
--> 328     oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
    329 else:
    330     raise TypeError("Accessing a group is done with bytes or str, "
    331                     " not {}".format(type(name)))

File h5py/_objects.pyx:54, in h5py._objects.with_phil.wrapper()

File h5py/_objects.pyx:55, in h5py._objects.with_phil.wrapper()

File h5py/h5o.pyx:190, in h5py.h5o.open()

KeyError: 'Unable to open object (message not aligned)'

```

System Info:
- Ubuntu version: 20.04.5 LTS
- python version: 3.10.4 (acquired with Anaconda)
- h5py version: 3.7.0
- fsspec version: 2022.3.0 
- hdf5 version: 1.10.6

Thanks!

**Comment by ajelenak** [comment]
Turning on fsspec logging may give some clues:
`fsspec.utils.setup_logging(logger_name="fsspec.http")`.

I tried to check whether the web server supports range requests with `curl -I <url>` and the response did not have `Accept-Ranges` header.

**Comment by takluyver** [comment]
Indeed, the server doesn't seem to support range requests - I tried `curl --range 0-100 http://piweb....` and definitely got more than 100 bytes back. If you can't change the server, you will have to make a local copy of the file to read from one way or another.

I was surprised that fsspec doesn't raise an error in this case. You're getting a mysterious error message from HDF5 because, as far as I can tell, fsspec is passing the wrong data to it. I've just opened an issue about that: https://github.com/fsspec/filesystem_spec/issues/1140

**Comment by takluyver** [comment]
I made a PR for fsspec, which has been merged, but not yet released. Once it is released, you should get a meaningful error message in this case, telling you that the server doesn't support HTTP range requests, rather than a mysterious error from HDF5 thinking the file is corrupt.

However, if you access a file under 5 MB, or only access data in the first 5 MB, it's likely to work, because fsspec defaults to fetching a 5 MB chunk into its cache, and it can get the first chunk even if range requests don't work. Once you go beyond that chunk, it will try to fetch another chunk, at which point it fails.
