### ISSUE TITLE
S3 support

### ISSUE THREAD

**Issue by ItayVortex** [h5py/h5py#2188]
Is it possible to use `h5py` with s3 objects?
Currently my way of work is to download the whole file and then use `h5py` on the local file. In most cases I don't need the whole data and would like to use h5 for this case. Does the library support reading the relevant parts from s3 when needed?

**Comment by ajelenak** [comment]
Yes, it is possible. You have two options:

1. Use libhdf5's Read-Only S3 (ros3) virtual file driver (VFD). This VFD is a build-time option so not all libhdf5 installations may have it. The libhdf5 from the conda-forge package repository comes with it, but the libhdf5 from the pip-installed h5py does not. More info about `h5py.File` drivers is [here](https://docs.h5py.org/en/latest/high/file.html#file-drivers).
2. Use any of the Python packages for working with S3 as long as they provide a Python file-like object that represents an HDF5 file in S3. More on Python file-like objects in h5py is [here](https://docs.h5py.org/en/latest/high/file.html#python-file-like-objects). I always use the [s3fs](https://s3fs.readthedocs.io/en/stable/index.html) package and recommend it over the ros3 VFD because it supports more advanced S3 features.

**Comment by takluyver** [comment]
I think @ajelenak has answered this quite comprehensively. :slightly_smiling_face:
