### ISSUE TITLE
how to add ros3 support

### ISSUE THREAD

**Issue by gilv** [h5py/h5py#2226]
I am using h5py version 3.8.0. How to add ros3 support? I saw other similar issues, but seems it was resolved in 3.2.. but I see the same error : "h5py was built without ROS3 support, can't use ros3 driver"

`
>>> print (h5py.__version__)
3.8.0
>>> h5py.registered_drivers()
frozenset({'family', 'fileobj', 'mpio', 'sec2', 'core', 'stdio', 'split'})
>>> 
`

**Comment by ajelenak** [comment]
See [documentation](https://docs.h5py.org/en/latest/high/file.html#file-drivers) for the ros3 driver. This was added just a few days ago.

I personally prefer the s3fs package. It is a much better interface to S3 and I do not need to think whether libhdf5 was built with ros3 support or not. And if you include the fsspec package (it works with s3fs in the background) then you will get the same file-like object access to many other storage systems.

**Comment by ajelenak** [comment]
h5py exposes various features only if they are available in the libhdf5 that it is using. The libhdf5 included in the h5py wheels does not have ros3 driver. Install h5py and libhdf5 from conda-forge.

Both s3fs and ros3 typically do not work very well because HDF5 files are not cloud-friendly by default. You have to either create cloud-optimized files or `h5repack` existing ones. But this topic moves away from h5py...

**Comment by takluyver** [comment]
Thanks @ajelenak ! I think you've covered this well, but just to say the same thing again: ROS3 is an optional feature that has to be enabled when compiling HDF5. It's off by default in the HDF5 code, and we don't enable it for our pre-built packages on PyPI, because that would mean bundling additional libraries.

Unfortunately using s3fs comes with some potential issues as well, because HDF5 doesn't really expect a custom file driver to run code in a dynamic language. But it's at least easier to get started with.

**Comment by gilv** [comment]
@takluyver how to enable build with ros3?

**Comment by takluyver** [comment]
The 'easy' way if it works for you is to get h5py from [conda-forge](https://conda-forge.org/), which builds with the feature enabled by default.

If that's not practical for you, you'll need to [build HDF5 from source](https://portal.hdfgroup.org/display/knowledge/How+do+I+build+HDF5+from+source) with the `--enable-ros3-vfd` configure option (or the `HDF5_ENABLE_ROS3_VFD` option in CMake). Then [build h5py from source](https://docs.h5py.org/en/stable/build.html#source-installation) to use that.

(If you're not familiar with compiling C code, you probably want to take one of the shortcuts we've mentioned - s3fs or conda-forge. Building C code isn't exactly *hard*, but there are a lot of ways it can go wrong, and it's hard to give general instructions that work for everyone. This goes doubly if you're on Windows.)
