### ISSUE TITLE
Parallel processing of large arrays

### ISSUE THREAD

**Issue by LogWell** [h5py/h5py#2288]
I have a large array (`10000x512x512x3`) stored in h5, I need to perform `Canny Edge Detection` on each image (`512x512x3`), how can I parallel this process?

**Comment by takluyver** [comment]
This is kind of nebulous; you might be better off looking for answers on [Stackoverflow](https://stackoverflow.com/), although I suspect that people will still want a bit more detail there.

Where h5py is concerned, be aware that HDF5 will only let one thread in a process access HDF5 files at a time. If you need to parallelise reading, you'll therefore need multiple processes. However, if reading is already much faster than processing, you might be OK with reading images one by one and parallelising the processing.

I'm going to close this because it's not really an h5py issue.
