### ISSUE TITLE
oserror: unable to synchronously open file (truncated file: eof = 2940928, sblock->base_addr = 0, stored_eof = 4107541)

### ISSUE THREAD

**Issue by katherine-Z-kx** [h5py/h5py#2340]
Hello, I have a problem like the title. My environment: python=3.8.18, h5py=3.10.0，pytorch=1.9.0 and windows 10.  When I trained the neural network, this error occurred every 43 epochs. I try to set numworks=0, or numworks=8, but this error still occurs.  Can anyone help me? please.

**Comment by takluyver** [comment]
Unfortunately, that error message usually means that the file has got corrupted. I've no idea why it would occur in a regular pattern, though. You may need to start with pytorch to understand what it's doing with h5py - the `numworks` parameter means nothing to me, for instance.

**Comment by Ofir408** [comment]
@katherine-Z-kx I have the same error. How did you solve it?

**Comment by Lsz-20** [comment]
The same question

**Comment by takluyver** [comment]
I'm going to close this because it doesn't seem like there's any particular bug for h5py to solve. The error message means the HDF5 file is corrupted. If that's happening often, there's a bug or a misconfiguration *somewhere* - probably not in h5py, though it is possible - and more details will be needed to figure out what's going on.
