### ISSUE TITLE
Clarify description of parallel hdf5

### ISSUE THREAD

**Issue by Wainberg** [h5py/h5py#2372]
The first line of https://docs.h5py.org/en/stable/mpi.html says:

> Read-only parallel access to HDF5 files works with no special preparation: each process should open the file independently and read data normally (avoid opening the file and then forking).

It would be worth clarifying the part in brackets: read-only parallel access _only_ works if the file is opened in separate processes. If you using either forking or multithreading, you will either get locking (if the library is compiled with --enable-threadsafe) or errors due to corruption of the internal state of the HDF5 library (if not).

**Comment by aragilar** [comment]
@Wainberg A PR expanding on this would be welcome (it may be worth adding to the FAQ as well).

**Comment by Wainberg** [comment]
I'm a bit too overloaded at the moment to submit a PR ;) but glad you agree the change is worth making!

**Comment by takluyver** [comment]
> If you using either forking or multithreading, you will either get locking (if the library is compiled with --enable-threadsafe) ...

Even with HDF5 built with thread safety, you could/can get weird effects after forking with an open file. HDF5 and h5py both use locks to prevent concurrent threads from affecting each other, but they don't protect against separate processes. Forked processes share their file descriptions, so a `seek()` in either process affects the offset in both. This used to be a problem in HDF5, but from 1.10.5 (I think), it uses `pread()` rather than seek+read, and now reading after forking generally seems to be OK. But there could still be issues in rarer cases.

I obviously don't want to explain all that right at the top of the page, but I'll try to clarify that sentence.

**Comment by takluyver** [comment]
#2411 is my attempt to make this clearer.
