### ISSUE TITLE
With numpy 2 (and h5py 3.11) all integers get written as np.int64 and it breaks things.

### ISSUE THREAD

**Issue by steven-murray** [h5py/h5py#2456]
* Operating System: Ubuntu
 * Python version: 3.11
 * h5py version: 3.11
 * HDF5 version: 1.14.2

Since numpy v2 (and h5py 3.11) if I do:

```
a = 1
with h5py.File('tmp.h5', 'w') as fl:
    fl.attrs['a'] = a

with h5py.File('tmp.h5', 'r') as fl:
    new_a = fl.attrs['a']
```

Then `new_a` has type `np.int64` rather than `int`. This is fine for some purposes, i.e. I can do `a == new_a` and it returns a truthy value (`np.True_` now instead of `True`). However, the string representation of the values is different (`1` vs. `np.int64(1)`) which can break APIs (e.g. I have code that writes files based on the hash of an object, which is now changed). 

Is this intended, and what is the suggested way to deal with such a change?

**Comment by neutrinoceros** [comment]
> Then new_a has type np.int64 rather than int. 

To be clear, `new_a` also has type `np.int64` with numpy 1, only the string representation differs.

**Comment by neutrinoceros** [comment]
For reference, here's the reference document describing this change in Numpy 2 https://numpy.org/neps/nep-0051-scalar-representation.html

**Comment by tacaswell** [comment]
I agree with @neutrinoceros , this does not look like a behavior change with h5py:

```
In [7]: import h5py
   ...: import numpy as np
   ...:
   ...: a = 1
   ...: with h5py.File('tmp.h5', 'w') as fl:
   ...:     fl.attrs['a'] = a
   ...:
   ...: with h5py.File('tmp.h5', 'r') as fl:
   ...:     new_a = fl.attrs['a']
   ...:
   ...: print(f'{np.__version__=}')
   ...: print(f'{a=} {type(a)=} {hash(a)=}')
   ...: print(f'{new_a=} {type(new_a)=} {hash(new_a)=}')
   ...:
   ...:
np.__version__='2.0.0'
a=1 type(a)=<class 'int'> hash(a)=1
new_a=np.int64(1) type(new_a)=<class 'numpy.int64'> hash(new_a)=1
```

vs

```
In [1]: import h5py
   ...: import numpy as np
   ...:
   ...: a = 1
   ...: with h5py.File('tmp.h5', 'w') as fl:
   ...:     fl.attrs['a'] = a
   ...:
   ...: with h5py.File('tmp.h5', 'r') as fl:
   ...:     new_a = fl.attrs['a']
   ...:
   ...: print(f'{np.__version__=}')
   ...: print(f'{a=} {type(a)=} {hash(a)=}')
   ...: print(f'{new_a=} {type(new_a)=} {hash(new_a)=}')
np.__version__='1.26.4'
a=1 type(a)=<class 'int'> hash(a)=1
new_a=1 type(new_a)=<class 'numpy.int64'> hash(new_a)=1
```

could you provide a minimal example that is now breaking?

**Comment by steven-murray** [comment]
Ah, I see what's going on. In my case I have some class which has a method that writes instances to a hdf5 file, e.g. (not the real example...):

```python
class Data:
    a: int
    b: np.ndarray

    def write(self, fname):
        with h5py.File(fname, 'w') as fl:
            fl.attrs['a'] = self.a
            fl['b'] = self.b

    @classmethod
    def from_file(cls, fname):
        with h5py.File(fname,'r') as fl:
            a = fl.attrs['a']
            b = fl['b'][()]
        return cls(a=a, b=b)

    def __repr__(self):
        return f"{self.a}"
```

And for testing, I have tests that do roundtrip testing of the read/write, e.g.:

```python
def test_roundtrip():
    c = Data(a=1, b=np.zeros(3))
    c.write('tmp.h5')
    d = Data.from_file('tmp.h5')
    assert c==d
    assert repr(c) == repr(d)
```

Of course, the last line is failing. It's slightly worse than this because the class also defaults to choosing its own filename when writing, based on the hash of the repr of the instance, which helps with caching. So that hash is now different if I have read the data in from file vs. creating the instance the standard way. It can be fixed simply by knowing ahead of time that I need to convert the `fl.attrs['a']` to `int` in the `from_file()` method, but this can get a little clunky when the attributes that are integers is more dynamic. 

Anyway, as you say, not specifically a problem with h5py (though I guess it would be nice if when you wrote integer attributes they would be read back in as ints, not np.int

**Comment by tacaswell** [comment]
Python ints are not strictly represent able in hdf5's type system.  Python's int is not fixed size (e.g. `2**1000` gives you the right answer where as `np.int64(2)**1000` overflows and does not) however all of numpy's types can be expressed in hdf5's system (which can also express things like non-standard width floats which numpy can not) and all I/O to hdf5 go through numpy's type system.  There is no way in the hdf5 type system to natively mark an int as "really" a Python int and maintain interoperability with reader/writers in other languages.  We could make a set of custom int types in the hdf5 file, but then other things could not read it.  We could also add extra attributes to specify how to cast the main one on read, but I think that would get too fussy very fast.

----

I am very skeptical of relying on the hash of the repr for anything.  There is almost no context where I would consider a repr/str change to be a breaking API change (as they are meant for humans to look at and understand rather than for another machine to consume).  That said, numpy preserved the old behavior of `str` so you can probably switch to that instead of repr (which should work with both old and new numpy).

----

I am going to close this as I do not think there is any action we can take on the h5py side of things.
