### ISSUE TITLE
h5py 3.12: import error on Windows

### ISSUE THREAD

**Issue by robomics** [h5py/h5py#2505]
Attempting to import a freshly installed version of `h5py` on Windows results in the following import error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\hostedtoolcache\windows\Python\3.[12](https://github.com/robomics/2024-09-25-h5py-bugreport/actions/runs/11038497694/job/30661854085#step:5:13).6\x64\Lib\site-packages\h5py\__init__.py", line 25, in <module>
    from . import _errors
ImportError: DLL load failed while importing _errors: The specified module could not be found.
```

I managed to reproduce this bug on `windows-latest` images on GitHub Actions using Python 3.9-3.12.

See the most recent workflow run [here](https://github.com/robomics/2024-09-25-h5py-bugreport/actions/workflows/ci.yml) for more details.

**Comment by takluyver** [comment]
Based on the number of reactions this has got in a few hours, I've yanked the 3.12.0 release for now until we have a better idea what's going on. I may still un-yank it again if it turns out that only a small fraction of Windows users are affected, although I don't know how I'd find that out.

I'm about to go to bed, and it's not easy for me to debug Windows issues even when I'm awake, since I don't have a convenient Windows machine to test on. So it would be good if some of the affected Windows users can investigate further.

Some clues:

-  Yanked releases aren't deleted, you can still download them [from PyPI](https://pypi.org/project/h5py/3.12.0/#files), or by specifying `pip install h5py==3.12.0`.
- We changed the CI platform on which we build wheels since 3.11, so it's likely that something to do with the new Github actions CI is the culprit. #2444 was the main PR for this.
- We do test the wheels after building them ([e.g. this CI run](https://github.com/h5py/h5py/actions/runs/11036731225/job/30655879090)), and they're passing the tests in our CI.
- I know of an ancient but useful tool for investigating these DLL load errors: https://dependencywalker.com/

**Comment by takluyver** [comment]
Actually, it might be quite simple. When building Windows wheels on the old CI, we called a script `bundle_hdf5_whl.py`:

https://github.com/h5py/h5py/blob/3.11.0/ci/azure-pipelines-wheels.yml#L59

I don't think this is called anywhere in the new CI. That's meant to copy the HDF5 DLLs into the Windows wheels (like a simplified version of `auditwheel` on Linux or `delocate` on Mac).

So, while I'm asleep, it would be great if someone could confirm if that is the cause, and figure out how to do it in the new CI config.

**Comment by robomics** [comment]
Thanks for the pointers!
I am afraid we live on a similar timezone, as I am also about to head to bed.

Unfortunately, unless the problem turns out to be trivial, I won't be able to look into it before this week-end :/.

> So, while I'm asleep, it would be great if someone could confirm if that is the cause, and figure out how to do it in the new CI config.

I downloaded and unzipped one of the wheels for macos and Windows. The `_errors .dll/.so` appears into both wheels.

<details>
  <summary>h5py-3.12.0-cp312-cp312-macosx_11_0_arm64.whl</summary>
  
  ```console
  ls -lah h5py-3.12.0-cp312-cp312-macosx_11_0_arm64.whl
  total 4.9M
drwxr-xr-x  5 roby roby  660 Sep 25 16:03 .
drwxrwxrwt 46 root root 1.4K Sep 26 01:27 ..
drwxr-xr-x  2 roby roby  100 Sep 25 16:03 .dylibs
drwxr-xr-x  2 roby roby  300 Sep 25 16:03 _hl
drwxr-xr-x  4 roby roby  780 Sep 25 16:03 tests
-rwxr-xr-x  1 roby roby 259K Sep 25 16:03 _conv.cpython-312-darwin.so
-rwxr-xr-x  1 roby roby 367K Sep 25 16:03 defs.cpython-312-darwin.so
-rwxr-xr-x  1 roby roby 118K Sep 25 16:03 _errors.cpython-312-darwin.so
-rwxr-xr-x  1 roby roby 122K Sep 25 16:03 h5ac.cpython-312-darwin.so
-rwxr-xr-x  1 roby roby 194K Sep 25 16:03 h5a.cpython-312-darwin.so
-rwxr-xr-x  1 roby roby 159K Sep 25 16:03 h5.cpython-312-darwin.so
-rwxr-xr-x  1 roby roby 312K Sep 25 16:03 h5d.cpython-312-darwin.so
-rwxr-xr-x  1 roby roby 138K Sep 25 16:03 h5ds.cpython-312-darwin.so
-rwxr-xr-x  1 roby roby 214K Sep 25 16:03 h5f.cpython-312-darwin.so
-rwxr-xr-x  1 roby roby 219K Sep 25 16:03 h5fd.cpython-312-darwin.so
-rwxr-xr-x  1 roby roby 233K Sep 25 16:03 h5g.cpython-312-darwin.so
-rwxr-xr-x  1 roby roby 118K Sep 25 16:03 h5i.cpython-312-darwin.so
-rwxr-xr-x  1 roby roby 175K Sep 25 16:03 h5l.cpython-312-darwin.so
-rwxr-xr-x  1 roby roby 184K Sep 25 16:03 h5o.cpython-312-darwin.so
-rwxr-xr-x  1 roby roby 496K Sep 25 16:03 h5p.cpython-312-darwin.so
-rwxr-xr-x  1 roby roby 116K Sep 25 16:03 h5pl.cpython-312-darwin.so
-rw-r--r--  1 roby roby  523 Sep 25 15:58 h5py_warnings.py
-rwxr-xr-x  1 roby roby 137K Sep 25 16:03 h5r.cpython-312-darwin.so
-rwxr-xr-x  1 roby roby 192K Sep 25 16:03 h5s.cpython-312-darwin.so
-rwxr-xr-x  1 roby roby 475K Sep 25 16:03 h5t.cpython-312-darwin.so
-rwxr-xr-x  1 roby roby 118K Sep 25 16:03 h5z.cpython-312-darwin.so
-rw-r--r--  1 roby roby 3.6K Sep 25 15:58 __init__.py
-rw-r--r--  1 roby roby 3.7K Sep 25 15:58 ipy_completer.py
-rwxr-xr-x  1 roby roby 196K Sep 25 16:03 _objects.cpython-312-darwin.so
-rwxr-xr-x  1 roby roby  93K Sep 25 16:03 _proxy.cpython-312-darwin.so
-rwxr-xr-x  1 roby roby 216K Sep 25 16:03 _selector.cpython-312-darwin.so
-rwxr-xr-x  1 roby roby 120K Sep 25 16:03 utils.cpython-312-darwin.so
-rw-r--r--  1 roby roby 1.9K Sep 25 15:58 version.py
  ```

</details>


<details>
  <summary>h5py-3.12.0-cp312-cp312-win_amd64.whl</summary>

  ```console
  total 3.2M
drwxr-x---  4 roby roby  640 Sep 25 21:28 .
drwxrwxrwt 46 root root 1.4K Sep 26 01:27 ..
drwxr-x---  2 roby roby  300 Sep 25 21:28 _hl
drwxr-x---  4 roby roby  780 Sep 25 21:28 tests
-rw-rw-rw-  1 roby roby 181K Sep 25 16:08 _conv.cp312-win_amd64.pyd
-rw-rw-rw-  1 roby roby 216K Sep 25 16:08 defs.cp312-win_amd64.pyd
-rw-rw-rw-  1 roby roby  50K Sep 25 16:08 _errors.cp312-win_amd64.pyd
-rw-rw-rw-  1 roby roby  55K Sep 25 16:08 h5ac.cp312-win_amd64.pyd
-rw-rw-rw-  1 roby roby 127K Sep 25 16:08 h5a.cp312-win_amd64.pyd
-rw-rw-rw-  1 roby roby  90K Sep 25 16:08 h5.cp312-win_amd64.pyd
-rw-rw-rw-  1 roby roby 253K Sep 25 16:08 h5d.cp312-win_amd64.pyd
-rw-rw-rw-  1 roby roby  79K Sep 25 16:08 h5ds.cp312-win_amd64.pyd
-rw-rw-rw-  1 roby roby 143K Sep 25 16:08 h5f.cp312-win_amd64.pyd
-rw-rw-rw-  1 roby roby 153K Sep 25 16:08 h5fd.cp312-win_amd64.pyd
-rw-rw-rw-  1 roby roby 155K Sep 25 16:08 h5g.cp312-win_amd64.pyd
-rw-rw-rw-  1 roby roby  59K Sep 25 16:08 h5i.cp312-win_amd64.pyd
-rw-rw-rw-  1 roby roby 105K Sep 25 16:08 h5l.cp312-win_amd64.pyd
-rw-rw-rw-  1 roby roby 125K Sep 25 16:08 h5o.cp312-win_amd64.pyd
-rw-rw-rw-  1 roby roby 416K Sep 25 16:08 h5p.cp312-win_amd64.pyd
-rw-rw-rw-  1 roby roby  47K Sep 25 16:08 h5pl.cp312-win_amd64.pyd
-rw-rw-rw-  1 roby roby  544 Sep 25 15:58 h5py_warnings.py
-rw-rw-rw-  1 roby roby  70K Sep 25 16:08 h5r.cp312-win_amd64.pyd
-rw-rw-rw-  1 roby roby 123K Sep 25 16:08 h5s.cp312-win_amd64.pyd
-rw-rw-rw-  1 roby roby 369K Sep 25 16:08 h5t.cp312-win_amd64.pyd
-rw-rw-rw-  1 roby roby  52K Sep 25 16:08 h5z.cp312-win_amd64.pyd
-rw-rw-rw-  1 roby roby 3.7K Sep 25 15:58 __init__.py
-rw-rw-rw-  1 roby roby 3.8K Sep 25 15:58 ipy_completer.py
-rw-rw-rw-  1 roby roby 114K Sep 25 16:08 _objects.cp312-win_amd64.pyd
-rw-rw-rw-  1 roby roby  39K Sep 25 16:08 _proxy.cp312-win_amd64.pyd
-rw-rw-rw-  1 roby roby 135K Sep 25 16:08 _selector.cp312-win_amd64.pyd
-rw-rw-rw-  1 roby roby  58K Sep 25 16:08 utils.cp312-win_amd64.pyd
-rw-rw-rw-  1 roby roby 2.0K Sep 25 15:58 version.py
  ```

</details>

So the problem seems to be a bit more complex.

I guess there must be something that makes the DLL not loadable on Windows.

**Comment by john-science** [comment]
> I may still un-yank it again if it turns out that only a small fraction of Windows users are affected

@takluyver I am not a Windows guy, but at work we can reproduce this bug on three different Windows systems:

* A co-workers Windows laptop (new Windows)
* The old Windows Jenkins machine (very old Windows)
* The GitHub CI (super minimal Windows variant)

Just FYI. Sorry I can't be more help.

**Comment by robomics** [comment]
I did a bit more digging, and found that the Windows wheels for 3.12 lack the usual dlls (which is why loading `_errors.pyd` fails).

Compared to wheels for h5py 3.11, the following dlls are missing:

```
-rw-rw-rw- 1 roby roby 3.3M Apr  2 15:35 h5py-3.11-win/hdf5.dll
-rw-rw-rw- 1 roby roby 115K Apr  2 15:35 h5py-3.11-win/hdf5_hl.dll
-rw-rw-rw- 1 roby roby  84K Oct  4  2017 h5py-3.11-win/zlib.dll
```

**Comment by neutrinoceros** [comment]
Thanks everyone for your inputs ! I've started looking into this and I think I've identified two reasons why this problem crept in without us noticing:
- not running `bundle_hdf5_whl.py` doesn't make a difference in the way our wheels are tested since it's always been run *after* testing
- we have infrastructure set up to upload nightly builds *for all platforms*, but this job never succeeded for h5py 3.12 due to requiring numpy>=2.1.0dev0 even on CPython 3.9 (which numpy 2.1 doesn't support).

I'm running experiments on my fork right now and will hopefully be able to issue a hotfix in a couple minutes.
Meanwhile, I encourage everyone interested in this failure to setup tests against our nightly builds at https://pypi.anaconda.org/scientific-python-nightly-wheels/simple/ so hopefully we can catch the next such mistake *before* the actual release.

**Comment by takluyver** [comment]
Thanks @robomics - those missing DLLs fit with not running `bundle_hdf5_whl.py`. I hope you got a decent amount of sleep as well!

I wonder if I yanked it too quickly and not enough of the US contingent saw the bug to get someone investigating. :laughing: 

Thanks @neutrinoceros - I'm happy to review a PR when you've got something, or work together on it if that would be useful.

**Comment by takluyver** [comment]
Windows users: the CI for that PR will produce wheels in a few more minutes, which will be available on this page:

https://github.com/h5py/h5py/actions/runs/11048098273?pr=2507#artifacts

Please could someone on a Windows system download these, install the one for your Python version (you can point `pip install` at the `.whl` file) and check if the issue is solved?

**Comment by robomics** [comment]
That seems to do the trick!

I don't have a Windows installed on bare-metal, but I could test the new wheels in a VM:

```python-console
Python 3.12.5 (tags/v3.12.5:ff3bc82, Aug  6 2024, 20:45:27) [MSC v.1940 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.27.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import platform

In [2]: platform.platform()
Out[2]: 'Windows-11-10.0.22631-SP0'

In [3]: platform.python_version()
Out[3]: '3.12.5'

In [4]: import h5py

In [5]:
```

**Comment by takluyver** [comment]
Thanks for testing it! I'll do a 3.12.1 release soon.

**Comment by takluyver** [comment]
OK, 3.12.1 is out now, which I believe fixes this issue.

**Comment by robomics** [comment]
Thank you both for the quick fix and release!
