### ISSUE TITLE
support CORE initialization from in-memory images

### ISSUE THREAD

**Issue by dnelson86** [h5py/h5py#552]
Hi,

A feature request to support operations on in-memory HDF5 image files.
In particular, to be able to initialize the CORE driver with an in-memory buffer

```
H5Pset_file_image(fapl_id, buf, buf_len);
```

These are 1.8.9+ features.

See page 24 of: http://www.hdfgroup.org/HDF5/doc/Advanced/FileImageOperations/HDF5FileImageOperations.pdf

Thanks!

**Comment by andrewcollette** [comment]
No objection from me!  A community-supplied PR would be necessary, though.

**Comment by dnelson86** [comment]
Relevant:

https://groups.google.com/forum/#!topic/h5py/W25rGn4msmM

**Comment by gheber** [comment]
+1 from me. I just thought about that very function the other day playing w/ PySpark.

**Comment by shoyer** [comment]
I am also very interested in this feature, but I'm not familiar enough with C to write the PR myself.

Note that pytables has support for this, which might might be a helpful starting point: 
https://pytables.github.io/cookbook/inmemory_hdf5_files.html#memory-images-of-hdf5-files

That final example seems to be missing the argument `driver_core_image=image`:
https://github.com/xray/xray/issues/23#issuecomment-36185024

**Comment by nevion** [comment]
I had this ready some time ago, but haven't had time to address what we wanted to do for the future:
https://github.com/h5py/h5py/pull/460

Been using it roughly every day since so it's definitely working for me.  

What we wanted to do was proper buffer handling though which required some changes to the callbacks the HDF group uses.  In my experience to date, it is quite the crap shoot getting them to accept patches and I haven't had time to even make them.

**Comment by gheber** [comment]
What kind of changes would you like to see? I'd be happy to shepherd things on this end.

**Comment by nevion** [comment]
@gheber I can expand more concretely if needed but basically we need to be able to control the lifetime management of a python c buffer object and have that be part of the H5LT functions/structs.  It is not sufficient to assume we can just pass the file image alone since we need to reference count on the python object to make sure the pointer the buffer/file image is working with stays valid.  Copying the image works for some people but given people using HDF5 are often using significant chunks (close to 100%) of ram, copying is not an option that works for many quite often, myself included.

So this means more callbacks and pointers need to be added to the H5LT.c file image functions/structs or we need to duplicate most of those lines to work with python.  This problem will happen exactly the same for Matlab (provided they updated),  R, octave, et al so it would be good to make an easily pluggable  H5LT.c so we don't need to copy and paste it N times to get a working efficient solution.

**Comment by nevion** [comment]
bump - @gheber  - anything?

FYI just rebased my image support topic fork on 2.5.0: https://github.com/nevion/h5py

**Comment by rcatwood** [comment]
This sounds useful for me, for managing operations on 'very large' 3- or 4-dimensional images,  but I am not sure I understand it. Would it transparently be using mmap as in C , such that a process manipulating a subsection of the image would have a mmap of the file but then only read the part of the file that is actually operated upon, thus avoiding filling up the memory unnecessarily, where 2 or 4 processes on each computer node are operating on different parts of the same file?

**Comment by nevion** [comment]
@rcatwood  Nope, just regular old buffers/arrays.  Of course python can make an mmapped buffer work without HDF explicitly knowing about it.

**Comment by shoyer** [comment]
I think we can close this thanks to https://github.com/h5py/h5py/pull/1061, which adds supports for reading/writing Python file-like objects.

**Comment by tacaswell** [comment]
I think this is more directly addressed by https://github.com/h5py/h5py/pull/1075 but in either case, this can be closed.
