### ISSUE TITLE
Multi-threaded reads use only 100% CPU?

### ISSUE THREAD

**Issue by shoyer** [h5py/h5py#591]
It is possible to use to utilize multiple cores when reading compressed files with h5py and multi-threading?

I would think h5py could avoid using a lock, because the hdf5 libraries don't need to be protected by Python's GIL.

Related discussions:
https://github.com/ContinuumIO/dask/issues/326
https://github.com/xray/xray/issues/444#issuecomment-116165986

**Comment by andrewcollette** [comment]
Unfortunately HDF5 does not support any type of thread-level parallelism.  Even if we were to remove the locking on the Python side, thread-safe builds of HDF5 use a similar global lock to serialize API access.  This applies to everything, including compression/decompression that occurs during data transfer.

In the past we have tried releasing the GIL during read/write operations, so that at least other Python code can run during the process.  Because of HDF5's extensive use of callbacks, some of which can call into Python code, this had mixed results (lots of hard-to-reproduce segfaults).

**Comment by shoyer** [comment]
Thanks, this is super informative, even though it's kind of a bummer. I guess multiprocessing is our best option for concurrent reads?

I'll go ahead and add a thread lock to HDF5 reads. Otherwise, it seems like seg faults can pop up when using multithreading with misconfigured HDF5 installs (this is the issue described here https://github.com/xray/xray/issues/444).

**Comment by andrewcollette** [comment]
Yes, multiprocessing can be used for concurrent reads, provided the file is not open for writing anywhere.  It's generally recommended to open the file after the fork(), however, although I'm not sure whether this is really needed or just folklore.

As far as thread safety, you shouldn't have to do anything special.  Beginning with h5py 2.4.0, every public API function and method in h5py is protected by a single reentrant Python-side lock.  That way even non-thread-safe builds of HDF5 are supposed to be protected.  If the xray project can trace those segfaults to a particular issue or corner case for h5py please let us know.
