### ISSUE TITLE
Nicer API / syntactic sugar for regionrefs

### ISSUE THREAD

**Issue by aldanor** [h5py/h5py#612]
Here are a few suggestions based on my personal experience with regionrefs, wonder if this is something that would be welcomed in h5py.

The only thing you can do with a region reference is pass it as the indexer to slice the dataset that it was bound to. It is of no use for anything else (unless I'm missing some hidden functionality in h5py?)

With this in mind, maybe we could allow the regionrefs to respond the same API as the datasets themselves (or rather, a sensible read-only subset of the API), to reduce the otherwise inevitable boilerplate?

For instance:
```python
# `f` is a file with a dataset "/a"
r = f['a'].regionref[:10, :20]
r[:]  # --> f['a'][r]
r[:, :2]  # --> f['a'][r][:, :2]
r.astype(float)  # --> f['a'][r].astype(float)
r.shape # --> f['a'][r].shape
r.dtype  # --> f['a'][r].dtype
```

Given that you can store references themselves in datasets, getting the data out is a bit clunky right now:
```python
f['r'] = r  # store the regionref
# and now, get the data from /a sliced by ref in /r
data = f['a'][f['r'][()]]
```

Whereas it could be either

```python
data = f['r'][()][:]
```

or, for *scalar* datasets containing a single regionref, since `[:]` is not normally allowed anyway, maybe it wouldn't be too ambiguous to alias `[]`for `[()][:]`, so the above just becomes

```python
data = f['r'][:]
```

**Comment by andrewcollette** [comment]
Interesting idea.  But applying slicing to regionrefs suggests to the end user that they support partial I/O, which they don't.  In many cases, we can't determine the shape of the regionref, so the number of axes is not even well-defined.

**Comment by aldanor** [comment]
Well, one way, as I suggested, would be to just always extract the data referenced by regionref in full and then slice it, then basically numpy is responsible for all the slicing and you don't have to do anything. It's not like you can do anything else with regionref anyway? (i.e., that's the only way you would use it if you wanted a slice of the data referenced by it). The users would just have to be warned that it's not a partial I/O.

```python
>>> import h5py
>>> import numpy as np
>>> f = h5py.File('foo.h5', driver='core', backing_store=False)
>>> f['a'] = np.random.randint(-10, 10, (20, 4))
>>> f['r'] = f['a'].regionref[:10, 0]
>>> f['a'][f['r'][()]][1, 2, 3]  # could be just f['r'][1, 2, 3] with the same outcome
IndexError: too many indices for array
```

The suggested addition is nothing but a shortcut to the syntax that you would have to use anyway.

The other way would be to try and infer the indices of the final slice and do it manually -- but the chances are it's going to be slower in a lot of cases, and would be much less transparent.

**Comment by aldanor** [comment]
On an unrelated note, regarding the shape, correct me if I'm wrong but isn't it always going to have the same number of dimensions as the original dataset? E.g.,

```python
>>> f['a'][f['a'].regionref[0, 1]]
array([[-10]])
```

**Comment by andrewcollette** [comment]
Unfortunately no... HDF5 provides no dimension information for region references.  We use some heuristics to handle this.  Of course, selections that use e.g. overlapping hyperslabs do not even have a rectangular shape.

Since the proposed syntax would not involve HDF5 operations, I still think it's misleading to provide it as part of the h5py package, regardless of what the documentation would advise as far as partial I/O and performance is concerned.  It's also going to complicate an already very complex part of the h5py codebase.  So unless other information comes to light, I am inclined not to include this feature.

**Comment by aldanor** [comment]
@andrewcollette I see, thanks.

Well, how about just a single accessor, maybe a `read()` method to underline that's it's potentially a costly operation? Basically anything that would allow to extract the data referenced by the regionref directly without passing it as an index.

```python
f['ref'].read()[:10, :20]
```
Would this be better?

**Comment by andrewcollette** [comment]
Ultimately I just not convinced this feature is worth the implementation, maintenance and debugging effort.  The h5py API is already very complex and adding new syntax for slicing isn't a priority.

I'm going to mark this as wontfix, but please don't be discouraged.  I'm particularly glad you kick-started the discussion on Blosc, which will become important as the PyTables merger gets going.

**Comment by aldanor** [comment]
@andrewcollette No problem, and thanks for at least reading through this :)

I've read the sources in more detail, and indeed, in the current architecture, `Reference` has no idea what file it belongs (may belong to), right? Which means it won't be possible to easily implement what I suggested above.

Anyways, on to hacking on some blosc, I hope to get things moving since everyone will benefit.

**Comment by arvidfm** [comment]
I realize that this issue is already closed as wontfix, but I'd still like to take a moment to advocate for this feature (or at least a similar feature that might be simpler to implement---see the end of the comment), along with a use case:

I'm working with data that is inherently sequential, but also discontinuous. In particular, I'm working with audio data, where the data is collected from multiple different files. In some cases I want to treat the data as a single, large, unordered set (e.g. when normalizing the data, or when training a model, where I treat individual audio frames as separate examples), but in other cases I need to keep in mind what parts of the data come from the same file (e.g. when doing feature extraction, since it doesn't make sense to use a context window that includes both the end of one file and the beginning of another).

Since I don't want to concatenate the whole dataset every time I do the training, my solution is to store all the data as a single large dataset in the HDF5 file, while also defining nested sections (sections can contain subsections) in the dataset using metadata storing regionref objects pointing to the corresponding sections in the data.

Since I don't want to deal with the HDF5 files directly in my code, I've created an abstraction layer where sections are represented as Python objects. Now I'd like to extract slices of the data sections, *without reading the whole section into memory*, by indexing these section objects. In other words, I want to be able to take slices of the regionref objects.

While I could, instead of storing regionref objects, store the start and end points of each section explicitly and attempt to adjust the user-specified slice to fit within the bounds of the section, and then simply slice directly from the dataset object, this would in practice mean having to implement my own slicing semantics, including having to consider issues such as negative indices, out of bounds indices, step sizes, advanced indexing, etc, etc---issues that are seemingly already solved in the h5py codebase.

Another approach that might simplify the implementation a bit would be to make it possible to *transform* existing regionref objects by slicing from them rather than having the slice return actual data. So, for instance, `ref = dataset.regionref[10:30:2][1:-3:2]` would be equivalent to `ref = dataset.regionref[12:24:4]`, after which `ref` can be used to index `dataset` as usual.

Of course, there might be a better way to go about what I'm attempting here (and in practice #728 is already making things difficult for me), so I'd appreciate any suggestions for alternative approaches to the problem.
