### ISSUE TITLE
Allow 1D boolean indexing of 2d (or more) hdf datasets

### ISSUE THREAD

**Issue by MaxNoe** [h5py/h5py#626]
Consider a  dataset with shape `(a, b)`.

It would be very handy if one could do boolean indexing on the first index like this:

```
import h5py

with h5py.File('myfile.hdf5', 'r') as f:
    data = f.get('mygroup/mydata')
    
    a = data.shape[0]
    
    mask = np.random.randint(0, 2, a).astype(bool)

    masked_data = data[mask]
```

This is not possible, one has to provide a mask with shape `(a, b)` and then a flattend array is return which one has to reshape.

**Comment by andrewcollette** [comment]
You can accomplish a similar task by using a list of coordinates, obtained via e.g. ``myarray.nonzero()``.  As for per-axis boolean indexing, I agree it would be handy but I don't think there's much of an appetite for adding even more complicated aspects of fancy indexing to the library at the moment.  One thing we have learned over the years is that indexing-related features tend to be buggy and have a high ongoing maintenance cost, in part because fancy indexing doesn't map well to HDF5's selection mechanics.

Further discussion of such features would certainly be welcome on the mailing list.
