### ISSUE TITLE
Comparing References does not work

### ISSUE THREAD

**Issue by coderforlife** [h5py/h5py#629]
Two references to the same dataset/group are always not equal, for example:

    f['a'].ref == f['a'].ref

is always `False` even though clearly it should be true. The only time it is `True` is if you do:

    r = f['a'].ref
    r == r

which is trivially `True` since Python shortcuts the `==` when `is` is `True`.

Basically I think that `__eq__` and `__ne__` should be implemented for `Reference`s and should return equal when they reference the same dataset/group.

One side question about this, is it possible to get the number (or at least if >0) references to a dataset/group?

**Comment by andrewcollette** [comment]
This would certainly be nice, but there would have to be an HDF5-side function for testing reference equality.  Officially references are opaque objects.  We can't dereference them for equality testing because (1) it would be an inappropriate (and expensive) side effect of equality testing, and (2) you need to provide a file, dataset, or group object to carry out the dereferencing anyway, which isn't available to the ref object.

So unless you can find an "H5Requal" or similar function, I think this won't be possible to implement.

**Comment by coderforlife** [comment]
Aw well, too bad... Thanks for considering it though.
