### ISSUE TITLE
Attribute writes slow

### ISSUE THREAD

**Issue by init-random** [h5py/h5py#705]
Summary of the h5py configuration
---------------------------------

h5py    2.6.0
HDF5    1.8.16
Python  3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.11.0

Below is some code to setup some metadata so i can index the dataset by string ids instead of numeric index, `dset[dset.attrs['id']]`.

    h5 = h5py.File("/tmp/ds.h5", "w")
    dset = h5.create_dataset("ds", (100000, ), dtype='float32')
    # ids is a generator of strings of length 36
    for idx, id in enumerate(ids):
        dset.attrs[id] = idx

I am trying to do this ~100000 records. I did a test set of about 17K and the for loop took over 25 minutes. It will take hours to do the whole thing. So for example:

     %timeit dset.attrs['some_id'] = 17

    The slowest run took 9.12 times longer than the fastest. This could mean that an intermediate result is being cached.
    10000 loops, best of 3: 93.1 µs per loop

Am I missing something? I don't understand why this operation should take so long. I could write this data to a flat file is <5 seconds.

**Comment by andrewcollette** [comment]
The attribute mechanism in h5py isn't designed to be a fast general-purpose key/value store.  The design tradeoffs we made include a large amount of type checking and extra work to make e.g. overwriting existing attributes robust, rather than efficiently handling thousands of attributes.

For your application I would suggest building a Python dictionary, pickling it (using protocol 0), and storing the result in an HDF5 attribute or dataset.  Or, for a more portable HDF5-based solution you can store the map in a special-purpose dataset, and load it back into a dictionary in your application:

```
index_dset = f.create_dataset('index', (100000,), dtype=[("key", "S36"), ("row", "u8")])
```

**Comment by epourmal** [comment]
On HDF5 side one should consider using the latest file format when creating the file. This will help HDF5 to deal with the big number of attributes on an object.

Elena
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Elena Pourmal  The HDF Group  http://hdfgroup.org
1800 So. Oak St., Suite 203, Champaign IL 61820
217.531.6112
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




On Apr 27, 2016, at 8:21 AM, Andrew Collette <notifications@github.com<mailto:notifications@github.com>> wrote:


The attribute mechanism in h5py isn't designed to be a fast general-purpose key/value store. The design tradeoffs we made include a large amount of type checking and extra work to make e.g. overwriting existing attributes robust, rather than efficiently handling thousands of attributes.

For your application I would suggest building a Python dictionary, pickling it (using protocol 0), and storing the result in an HDF5 attribute or dataset. Or, for a more portable HDF5-based solution you can store the map in a special-purpose dataset, and load it back into a dictionary in your application:

index_dset = f.create_dataset('index', (100000,), dtype=[("key", "S36"), ("row", "u8")])

**Comment by jreadey** [comment]
@epourmal's suggestion is well worth trying out.  I've found that attribute access was much faster using the latest file format.  When creating the file just add the libver parameter. E.g: `` f = h5py.File(filePath, mode, libver='latest')``

**Comment by init-random** [comment]
Thanks everyone for the ideas! I will try them out.

**Comment by tkorach** [comment]
Can report from my experience - it achieved a speed-up of several orders of magnitude.
