### ISSUE TITLE
Consider creating anylinux wheels for PyPI

### ISSUE THREAD

**Issue by estan** [h5py/h5py#706]
I was recently pleasantly surprised that NumPy now offers [manylinux](https://github.com/pypa/manylinux) wheels [on PyPI](https://pypi.python.org/pypi/numpy), which makes installation a breeze when installing with pip in a virtualenv, as it doesn't have to be compiled. This was especially nice for us as we use virtualenv + pip + Docker containers as test environments (even on developer's machines).

I then noticed that h5py is the only non-Python-only dependency we still have that doesn't offer anylinux wheels on PyPI. I don't know how feasible it would be, but it would be awesome if h5py could be offered as wheels, including anylinux variants, as it makes for so much speedier installation.

**Comment by tacaswell** [comment]
I suspect the sticking point here will be reliably bundling hdf5 and it's dependencies.

**Comment by estan** [comment]
I can appreciate it'll be some work, but it would bring convenience to so many people. Besides the cut down installation time, it'll also make people's virtualenvs more isolated, since there's less dependency on system-wide packages.

Looking at the dependencies of HDF5, they don't seem that many. Up until version 1.8.14, which should be supported by h5py, the HDF Group even offers [binary builds for Cent OS 5](https://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.14/bin/) that I believe could be used to build the wheels on Travis CI inside the Cent OS 5 Docker container provided by manylinux. I think bundling of the libraries would just be a matter of using the [auditwheel](https://pypi.python.org/pypi/auditwheel) tool as shown in the manylinux [demo project](https://github.com/pypa/python-manylinux-demo).

Of course there's probably some road bumps I'm not thinking of, but I don't think it would be that bloody :) PyQt 5.6 manylinux wheels were recently put up on PyPI, and those contain much more massive dependencies.

**Comment by aragilar** [comment]
The problem with manylinux wheels is there's only one configuration, and that pip etc. prefer wheels over building from source.

For the first issue, I suggest reading distutils-sig and numpy-dev for a full summary of the problems, but a quick summary: you can have one wheel per "configuration", where "configuration" is the collection of information that pip etc. know about your computer. While pip knows about i386 vs. amd64, it doesn't know fine details, such as what CPU you have (and so what SIMD optimisations it can use), and what libraries you have installed. Depending on the package, this may or may not be a problem.

In PyQt's case, this is easy, as whilst it has quite a few dependencies (see https://doc.qt.io/qt-5/linux-requirements.html for qt deps for example), they are either in the [allowed dependencies](https://www.python.org/dev/peps/pep-0513/#the-manylinux1-policy), or don't need multiple configurations.

However, with h5py, there are (at least) two distinct configurations, with or without MPI. Using MPI is an important use case for h5py, so breaking that is a bad idea (which is effectively what will happen if we distribute manylinux wheels without MPI). However, if we depend on MPI, then you require a manylinux wheel for mpi4py (which doesn't exist, and which has the same problems as h5py), so that doesn't work either. Having two wheels would work, but that isn't possible with wheels. The final solution is to get everyone (on linux) to build from source, which appears to be the only possible solution. We could create manylinux wheels, but not upload them to PyPI, but that not much of an advantage, and really, anyone could do that (this isn't entirely crazy, as it's effectively what [Christoph Gohlke](http://www.lfd.uci.edu/~gohlke/pythonlibs/) did on Windows). So building from source seems to be the best option.

My solution to this is to use [devpi](http://doc.devpi.net/latest/), which supports multiple indexes, and using (effectively, there some complexity here with fixing dependencies) pip wheel to build wheels. You could also use conda/canopy/etc.

As a side note, the binaries from the HDF group have some problematic licensing due to how they are built (which is why the Windows wheels don't use it).

**Comment by estan** [comment]
@aragilar: Thanks a lot for the detailed answer James!

I can appreciate the two problems you bring up, and I can see that the default experience for Linux users would be different from what it is today.

To summarize, if anylinux wheels were to be uploaded today, then by default, Linux users would get an unoptimized (e.g. no SIMD) "one size fits all" h5py unless specifying `--no-binary`. If they specify `--no-binary` it would be the same as it is today.

The points about parallell vs serial HDF5 I think are less of an issue though, since to get MPI the user will have to build from source today anyway, and will need to take special action to get it. The way I imagine it, MPI wheels of h5py would simply not be offered, and the docs would simply say to build from source if you want MPI, like they do now.

So the question is whether this is change of experience is acceptable. Personally I wouldn't mind it if the docs said something like "By default you'll get a binary wheel that is unoptimized (no SIMD et.c.) and configured like X, Y, Z. If you want a h5py tailored for your CPU, or want to change configure options (like enabling MPI), then you need to build from source.".

I don't see offering a "one size fits all x86" and a "one size fits all x64" binary by default as a problem. It's similar to how Linux distro packages work, where the user have to compile from source to get something more tailored to their system.

But this is all up to you folks of course. I just see the speedier installation and gained isolation when used in a virtualenv as great benefits compared to getting an SIMD-optimized h5py by default.

If the PyPI system is (hopefully) improved in the future with some sort of system to manage differently configured binary wheels, then that could be adopted as soon as it's available.

The licensing of the HDF5 group binaries you mention is unfortunate. But building it from source inside the Cent OS 5 container, and bundling the resulting shared library in the wheel using `auditwheel` should still be doable, right?

**Comment by estan** [comment]
I've now read the lengthy numpy-discussion thread titled "linux wheels coming soon" (is that the one you meant?). I couldn't find any concerns raised regarding users getting an unoptimized numpy by default. It seems most people (me included) were just happy that manylinux wheels were becoming available. Many seemed happy because their Travis builds were now faster. There was some discussion on whether to use ATLAS or OpenBLAS, but they settled on OpenBLAS since it seemed more robust.

I haven't read all of the distutils-sig threads on manylinux yet (huge!), but I'm assuming there's some discussion on support for multiple configuration options in there? Do you know roughly when those discussions took place? In any case, I personally think that until that issue is solved, there's still value in offering "one size fits all" manylinux wheels for h5py. Hopefully the system will be improved later.

Again, this is all of course up to you maintainers, but now I've at least stated my case :)

**Comment by tacaswell** [comment]
There is also this discussion: https://github.com/numpy/numpy/issues/7570

**Comment by estan** [comment]
@tacaswell: Thanks for the pointer. The issues brought up there seems to be that bundled libs trip up dh_strip/dh_shlibdeps from Debian packaging, and the (perhaps poor) practice of uploading binary wheels to a release after the fact.

I can agree those are road bumps, but I think users wishing to build Debian packages including h5py from PyPI should make sure they use `--no-binary`. I personally also thinks it's a little irresponsible to add binary wheels to long since made releases, since it risks breaking things (there's also a problem with hash checking with sdist when doing this, e.g. [https://github.com/pypa/pip/issues/3634](https://github.com/pypa/pip/issues/3634)), and I'm only suggesting h5py do this on new releases.

**Comment by jakirkham** [comment]
Alternatively, you could download [`h5py`]( https://github.com/conda-forge/h5py-feedstock ) with [`conda`]( http://conda.pydata.org/docs/ ) from [conda-forge]( http://conda-forge.github.io/ ).

**Comment by matthew-brett** [comment]
I've made a build grid for manylinux and OSX wheels here : https://travis-ci.org/MacPython/h5py-wheels

This builds and tests h5py wheels for all the combinations that manylinux supports, including 32-bit.

As for the OSX and Windows wheels (which have been up for ages) these wheels do a completely default libhdf5 build, and disable szip encoding, so as not to accidentally encumber the user with the patented technology.

I think the point here is to make the default case as simple and painless as possible, and the high-performance case possible.   For example, if you want CPU optimized MPI h5py, then presumably you are up to building these yourself, with a custom build of libhdf5, and `pip install --no-binary h5py h5py`.  If you do care about this level of performance, it seems to me that you would be unwise to rely on a default pip install from source.

Other projects with manylinux wheels now up are: numpy, scipy, cython, astropy, scikit-learn, scikit-image, pyzmq, among others.  I defer to Thomas here, but I believe we've agreed that matplotlib will be shipping wheels for the next release, and statsmodels wheels are ready to go when the next release comes up (soon).

Test the current build matrix wheels with:

```
python -m pip install --upgrade pip  # upgrade to latest pip
pip install -f https://3f23b170c54c2533c070-1c8a9b3114517dc5fe17b7c3f8c63a43.ssl.cf2.rackcdn.com h5py 
```

That takes about 3 seconds on my machine, which is a great pleasure to watch :)

**Comment by matthew-brett** [comment]
Y'all probably knew this, but it looks like NASA has abandoned the relevant patents for szip.  From https://www.hdfgroup.org/doc_resource/SZIP/Commercial_szip.html the patents are: 

```
United States Patent Nos. 5,448,642, 5,687,255, and 5,822,457
```

From: https://gitlab.dkrz.de/k202009/libaec/blob/master/doc/license.txt

```
The license agreement with ICs, LLC, for Patent Numbers US 5,448,642,
US 5,687,255 and US 5,822,457, has been terminated effective March 31,
2009. NASA has no other licensee of these patents. It is NASA's intent
to not pay the remaining maintenance fees owing on these patents,
thereby allowing them to eventually become abandoned, and to not
enforce the patents.
```

**Comment by andrewcollette** [comment]
@matthew-brett unfortunately the libszip implementation distributed by the HDF Group (the only one that exists?) is still subject to copyright, and is distributed with that ridiculous license from "ICs LLC".

**Comment by aragilar** [comment]
[libaec](https://gitlab.dkrz.de/k202009/libaec) can act as a replacement for SZIP, and is being used by Debian as a replacement (see https://packages.qa.debian.org/liba/libaec.html and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=811093), not that changes the contents of the file distributed by the HDF Group.

**Comment by matthew-brett** [comment]
Here I built the wheels with `libaec` and enabling encoding: https://travis-ci.org/MacPython/h5py-wheels/builds/139923044 .

**Comment by estan** [comment]
@matthew-brett: Many thanks for doing this work!

To h5py maintainers: Is there any chance that with the next release, these manylinux wheels could be made official and uploaded to PyPI?

**Comment by matthew-brett** [comment]
@andrewcollette - do you agree with my new wheel recipe - I mean, enabling szip encoding using libaec?

I updated the wheel-building instructions here : https://github.com/MacPython/h5py-wheels

Would you consider allowing me to upload the manylinux wheels for 2.6.0 ?   Or would you rather wait for the next release?    When is that likely to be?

**Comment by andrewcollette** [comment]
@matthew-brett, I don't have any substantial objections... the only concern I would have is regarding the amount of testing libaec has undergone being used with HDF5.  We don't have any tests in h5py specifically for szip, with the exception of basic stuff like making sure the options work.  Also pinging @jreadey in case the HDF Group has any opinion or experience using non-libszip implementations.

Regarding the manylinux wheels... again, no strong objections.  We are in a bit of a hiatus period right now for releases.  I don't personally have much free time to work on h5py these days, but I certainly don't want to act as a roadblock.  If there are folks in the community who would like to volunteer to move the release process forward I would be happy to engage with them, including advice and whatever access rights would be needed here or on PyPI.

**Comment by matthew-brett** [comment]
Given Debian and Ubuntu ship libaes, I suppose it must now be one of the more tested configurations with HDF5 in general.  I have the impression that Fedora etc don't ship any szip in their [hdf5 rpm](http://www.rpmfind.net/linux/RPM/fedora/24/x86_64/h/hdf5-1.8.16-3.fc24.x86_64.html).  For the binary wheels, I guess there has been no testing of szip encoding up till now, because the Windows and OSX wheels disabled it.  

It sounds like you think the next release is not imminent.  In that case, it would be good to ship the 2.6.0 wheels - the rest of the Scientific stack is almost there, matplotlib gets released with manylinux wheels in a day or so, and numpy, scipy, Pillow etc already have manylinux wheels on pypi.  I think having a good functional h5py available as a quick and simple install would be a big win.

**Comment by andrewcollette** [comment]
Sounds good to me.  You should already have PyPI access... let me know if you need anything.  Thanks again for investing the time to prepare these packages!

**Comment by estan** [comment]
> Sounds good to me. You should already have PyPI access... let me know if you need anything. Thanks again for investing the time to prepare these packages!

Many thanks from me as well! I'll be a very happy camper once this is on PyPI.

**Comment by matthew-brett** [comment]
OK - done.

Andrew - things got a bit sticky because, when I was trying to upload using the latest `twine`, the upload was going to the warehouse pypi server, and this has more aggressive checking of the author email address - giving:

```
HTTPError: 400 Client Error: author_email: Invalid email address. for url: https://upload.pypi.io/legacy/
```

I think this is because you have your email in name at host dot com form in the author and maintainer email field in `setup.py`.  Would you consider changing that to a proper email address to make the upload happy in the future?  I suspect that pypi is doing that to make it less likely that package maintainers become impossible to contact.

**Comment by aragilar** [comment]
Now that there are manylinux wheels on PyPI, either @estan or a h5py maintainer should close this issue.

**Comment by andreabedini** [comment]
@matthew-brett thanks for the suggestion, done in 0efacee
@aragilar thanks for the heads up
