### ISSUE TITLE
wrap dimension scale attributes in some way

### ISSUE THREAD

**Issue by equaeghe** [h5py/h5py#831]
Currently, when a dataset is made a dimension scale, it gets the attributes `'CLASS'`, `'NAME'`, and `'REFERENCE_LIST'`. Given that these are attributes that are not consciously created by the user, it would be user-friendly if they were wrapped in some way. Namely those attribute names should ideally be protected against use for user attributes, not shown when inspecting the `attrs` attribute, and the `'NAME'` and `'REFERENCE_LIST'` should be accessible through some other attribute(s) of `Dataset`. Specifically, the reference list is currently not very user friendly.

**Comment by takluyver** [comment]
I'd disagree on this one: I think it's better for h5py to expose what HDF5 is really doing, and leave the special attributes visible and accessible. I'd just add to the [attributes documentation](http://docs.h5py.org/en/latest/high/attr.html) details of which attribute names have special meaning for HDF5 itself.

This is in line with the 'consenting adults' principle Python often uses: we don't need to hide the machinery away to protect it from developers.

**Comment by aparamon** [comment]
Looks like another opportunity to (ab)use `h5py.get_config()` ;-)

**Comment by takluyver** [comment]
I'd just leave the code as it is and add some documentation of it. More config options is more to go wrong.

**Comment by aparamon** [comment]
Another crazy/brainstorm idea: what if [HLObject.attrs](https://github.com/h5py/h5py/blob/d3ba9449827a9dc33d6d75409805b71567c9973b/h5py/_hl/base.py#L268) was callable, i.e. [AttributeManager](https://github.com/h5py/h5py/blob/340ba1115fb12515bfc3d8d57c2ecf5667d3d6ea/h5py/_hl/attrs.py#L30) instance could be called with parameter e.g. `wrap_dimension_scale=True`? The resulting `AttributeManager` copy could provide a more user-friendly wrapper for `REFERENCE_LIST`, for example.

One other parameter fitting nicely there is iteration order, e.g. we could have both default, based on `track_order`
````py
list(dset.attrs)
````
and explicit
````py
list(dset.attrs(ordered=True))
list(dset.attrs(sorted=True))
````
Isn't it fancy? ;-)

In reality though it should be hard (but not impossible!) to find cases where the performance of the last line is superior to equally idiomatic
````py
sorted(dset.attrs)
````
----
A much more realistic idea is `Dataset.as_dimension_scale()` method which returns `DimensionScale` instance with all nice user-friendly interface. This keeps basic `HLObject.attrs` untouched and following HDF5 API.

**Comment by takluyver** [comment]
It all feels like a solution in search of a problem, frankly. There's already `.dims` to provide a nicer interface to dimension scales (though it could be clearer, e.g. #830, #832). As you noted, you can use `sorted()` to get a list of attributes reliably in name order.

I think it's more useful to focus on what problems there are, rather than what we could add. What can we not do with the current interface, or what is unnecessarily difficult or confusing?

The original issue here was that it's not user-friendly to expose attributes relating to the inner workings of HDF5. I don't see that as a problem: I think h5py should expose HDF5 as faithfully as practical to the Python world. Trying to deliberately hide parts of HDF5 ultimately makes more complexity to deal with - e.g. there has to be some special (i.e. surprising) behaviour if you try to set a value for a hidden attribute.

**Comment by aparamon** [comment]
@takluyver Ah, I didn't know `.dims` existed! It would useful to know what it doesn't provide for @equaeghe, indeed.
Agree with you that closely following HDF5 API, at least by default, is a virtue.

**Comment by takluyver** [comment]
I'm going to close this, as I don't think anyone has convincingly rebutted my argument for leaving the details visible. My word isn't final, though - if someone wants to make the case for it, we can reopen it.

But I don't want someone to assume that it's a desirable feature and spend time implementing it if there's a good chance we'd reject it anyway.
