### ISSUE TITLE
Non-square data returns Type Error: Can't broadcast error.

### ISSUE THREAD

**Issue by jubjamie** [h5py/h5py#844]
When I try to build a dataset using some code based on tflearn's datautils package I find that when trying to pass non-square data (e.g. image size 400x300) then I get a can't broadcast error. It looks like there is a problem because it's going from 3 parameters to 4 but then I don't understand why it would work with square data. Is this a bug, is it intended or is actually a user/implementation problem?

Error traceback below from running on Ubuntu in Jupyter/iPython.

Thanks

```
TypeError                                 Traceback (most recent call last)
<ipython-input-4-879273bf62a2> in <module>()
----> 1 datatools.build_hdf5_image_dataset(dataset_file, image_shape=(400,300), mode='folder', output_path='flowers_falsecat_HWtest2.h5', categorical_labels=False, files_extension='.jpg')
      2 

/mnt/c/Users/Trials/localBASH/project_p17/experimental/frames/mtools/datatools.pyc in build_hdf5_image_dataset(target_path, image_shape, output_path, mode, categorical_labels, normalize, grayscale, files_extension, chunks)
    157         if normalize:
    158             img /= 255.
--> 159         dataset['X'][i] = img
    160         if categorical_labels:
    161             dataset['Y'][i] = to_categorical([labels[i]], n_classes)[0]

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/tmp/pip-4rPeHA-build/h5py/_objects.c:2684)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/tmp/pip-4rPeHA-build/h5py/_objects.c:2642)()

/usr/local/lib/python2.7/dist-packages/h5py/_hl/dataset.pyc in __setitem__(self, args, val)
    615             mshape_pad = mshape
    616         mspace = h5s.create_simple(mshape_pad, (h5s.UNLIMITED,)*len(mshape_pad))
--> 617         for fspace in selection.broadcast(mshape):
    618             self.id.write(mspace, fspace, val, mtype, dxpl=self._dxpl)
    619 

/usr/local/lib/python2.7/dist-packages/h5py/_hl/selections.pyc in broadcast(self, target_shape)
    295                     tshape.append(t)
    296                 else:
--> 297                     raise TypeError("Can't broadcast %s -> %s" % (target_shape, count))
    298         tshape.reverse()
    299         tshape = tuple(tshape)

TypeError: Can't broadcast (300, 400, 3) -> (1, 400, 300, 3)
```

**Comment by awilliamson** [comment]
Having just received this error myself when working on TensorFlow. I believe the issue is caused on https://github.com/h5py/h5py/blob/c3be67f075ed067adfbfeb6038ee5f96b94dcf17/h5py/_hl/selections.py#L291
When inspecting variables. Count, Target, and Target_Shape are all utilised. The issue becomes that count ( which is used in the conditional for whether to throw or not ) has width and height reversed. Whereas Target, and Target_shape both have it the same way. Flipping input dimensions around causes all of them to flip. Therefore, it will never correctly work with a non-square input.

I am unsure which convention the developers wish to follow. Whether it's ( W, H ) or ( H, W ); as I understand OpenCV throws out Height first by shape. So a simple fix for now ( I would imagine ), is to patch your own selections implementation, and simply flip index 1 and 2 of the count list.

When I'm less sleep deprived, and have more time I'll attempt to look into the codebase properly and perhaps fix this and PR back. But currently, I am very unfamiliar with h5py, and I'm only using it to enable faster prefetching for my ML models.

**Comment by jubjamie** [comment]
@awilliamson That makes sense. I was kind of using TFLearn to start off with but now i'm only using the build dataset code which I have copied/forked from TFLearn. I don't actually use it anymore, just the dataset building code. Are you saying that if I match the PR you made then the issue should be resolved?

**Comment by awilliamson** [comment]
@jubjamie Should do, from preliminary testing it generates a valid hdf5 file, with appropriate labels and is non-square. Let me know if it works for you. If so, could you also confirm this on the PR itself, that would be greatly appreciated.

**Comment by jubjamie** [comment]
@awilliamson I will try and do it today. I think that we're both in agreement that the problem lies within TFLearn? If so I will close the issue.
