### ISSUE TITLE
Compression  doesn't compress data on SWMR

### ISSUE THREAD

**Issue by simondub** [h5py/h5py#980]
This can cause a dataset to take 800k on disk instead of 6 k for the uncompressed data version.
Possible explanation:
    Every time there is a flush on a chunk of a compressed file,  zip dictionary is updated. So the dictionnary can become extremely huge.

'Summary of the h5py configuration\n---------------------------------\n\nh5py    2.7.1\nHDF5    1.10.1\nPython  2.7.9 (default, Jun 29 2016, 13:08:31) \n[GCC 4.9.2]\nsys.platform    linux2\nsys.maxsize     9223372036854775807\nnumpy   1.13.3\n'

---Code example---
[testing_H5py_compression.py.zip](https://github.com/h5py/h5py/files/1632916/testing_H5py_compression.py.zip)

**Comment by aragilar** [comment]
Having a quick look at the SWMR code, it looks like this is a limitation of HDF5. It's worth asking on the HDF5 mailing list if anyone else has noticed this.

**Comment by aparamon** [comment]
A minimally reproducible example:
(albeit missing the motivation aspect for calling `dset.flush()` repeatedly in the loop)
````py
import h5py
import numpy as np

f = h5py.File('test.h5', 'w', libver='latest')
f.swmr_mode = True
arr = np.arange(1000).astype(np.float32)
dset = f.create_dataset('data', data=arr, chunks=(1000,), compression='gzip')
for i in range(1000):
    dset[i] = np.random.randn(1)
    dset.flush()
````
creates 2,295,175 bytes test.h5 as opposed to just 5,785 bytes when commenting out
````py
f.swmr_mode = True
````
The latter just calls [H5Fstart_swmr_write](https://support.hdfgroup.org/HDF5/doc/RM/H5F/H5Fstart_swmr_write.htm).

**Comment by rmvanhees** [comment]
Dear Andrey,

According to the HDF5_SWMR_Users_Guide
<https://support.hdfgroup.org/HDF5/docNewFeatures/SWMR/HDF5_SWMR_Users_Guide.pdf>,
you can not create new datasets in SWMR mode (see section 3).
I agree with you that the flush statement is unnecessary, or actually
introducing the problem: without the flush the file is 7051 bytes, with
2,283,312 bytes.
The file created without SWMR mode is slightly smaller, because in SWMR
mode the HDF5 library has to include checksums, etc. This is no problem for
files with larger datasets.

Therefore, the correct code should be:

f = h5py.File('test.h5', 'w', libver='latest')
arr = np.arange(1000).astype(np.float32)
dset = f.create_dataset('data', data=arr, chunks=(1000,), compression='gzip')
f.swmr_mode = True
for i in range(1000):
    dset[i] = np.random.randn(1)
    # dset.flush()

f.close()

**Comment by aparamon** [comment]
Thank you! I reported the issue upstream:
https://forum.hdfgroup.org/t/bug-compression-doesnt-compress-data-on-swmr/5280

**Comment by aparamon** [comment]
According to https://forum.hdfgroup.org/t/bug-compression-doesnt-compress-data-on-swmr/5280/2:
> It is not a bug but a feature: file space recycling is disabled in SWMR mode.
> 
> Every time the program flushes a chunk after adding a new element, the chunk is compressed and written to the file. When another element is written to the chunk and chunk is compressed and flushed, it is written to the new space in the file.
> 
> If you move out H5Fflush call outside “for loop”, file size is as expected because chunk stays in cache and is flushed when fully written.
> 
> This SWMR limitation is documented in SWMR User’s Guide https://portal.hdfgroup.org/display/HDF5/HDF5+Single-Writer+Multiple-Reader+User’s+Guide . See section 3 “SWMR Scope and Limitations”, 5th bullet. I guess we need to explain this better and your example is very helpful.

So, dataset update granularity in SWMR mode is effectively limited by chunk size.
